# Lectura de Datos

In [1]:
import scipy.io 
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.svm import SVC 
from auto_tqdm import tqdm
from sklearn.feature_selection import RFE
import pathlib
import typing
from typing import List, Tuple, Dict, Any, Callable, Type
import numpy.typing as npt
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator
from collections import Counter
Scaler = Type[BaseEstimator]
from datareader import *
from SAE import *

from featureselectors import RFE 

# Creating the algorithm of RFE using SAE for evaluation

# CUB - Train Val

In [2]:
#################
### Arguments ###
#################
class Arguments:
    def __init__(self, dataset,seed,mode):
        self.dataset = dataset
        self.seed = seed
        self.mode = mode
        
         
DECIMAL_NUMBERS        = 3
FOLDS                  = 5
scaler_str             = 'Standard'     # ['Standard','MinMax']
orig_attribute         = False # Attributos originales u otros
debug                  = True 
SHOW                   = True

step                     = 5  # Paso de atributos a seleccionar [a, a+step, a+2*step, ...]
hitk = 1    
args = Arguments('CUB',42,'rfe') # MODE = RFE


#################
##### SetUp #####
#################
random.seed(args.seed)
np.random.seed(args.seed)
print(f"You've selected {args.dataset} dataset")
print(f"You've selected {args.mode} mode")
random_mode = False if args.mode == 'rfe' else True 
rfe_mode    = False if args.mode == 'random' else True

# Set up the path to the data
# Set up the path to the data
path_dir                  = pathlib.Path('data/')
path_data                 = path_dir / args.dataset  
results_dir               = pathlib.Path(f'Results/HAIS_v2/{args.dataset}') 


path_results_rfe_train_val    = results_dir / f'Wrapper{args.dataset}-RFE-train-val.csv'
path_results_random_val       = results_dir / f'Wrapper{args.dataset}-Random-val.csv' 
path_results_rfe_val_val      = results_dir / f'Wrapper{args.dataset}-RFE-val-val.csv'
path_results_random_simple    = results_dir / f'Wrapper{args.dataset}-Random-simple.csv' 

path_masks_rfe_train_val    = results_dir / f'Masks_{args.dataset}-RFE-train-val.csv'
path_masks_random_val       = results_dir / f'Masks_{args.dataset}-Random-val.csv' 
path_masks_rfe_val_val      = results_dir / f'Masks_{args.dataset}-RFE-val-val.csv'
path_masks_random_simple    = results_dir / f'Masks_{args.dataset}-Random-simple.csv' 

path_oracle_rfe_train_val    = results_dir / f'Oracle_Wrapper_{args.dataset}-RFE-train-val.csv'
path_oracle_random_val       = results_dir / f'Oracle_Wrapper_{args.dataset}-Random-val.csv' 
path_oracle_rfe_val_val      = results_dir / f'Oracle_Wrapper_{args.dataset}-RFE-val-val.csv'
path_oracle_random_simple    = results_dir / f'Oracle_Wrapper_{args.dataset}-Random-simple.csv' 

path_conteo_rfe_train_val    = results_dir / f'Conteo_{args.dataset}-RFE-train-val.csv'
path_conteo_random_val       = results_dir / f'Conteo_{args.dataset}-Random-val.csv' 
path_conteo_rfe_val_val      = results_dir / f'Conteo_{args.dataset}-RFE-val-val.csv'
path_conteo_random_simple    = results_dir / f'Conteo_{args.dataset}-Random-simple.csv' 



# Load the data
matcontent, att_splits = load_data_from_path(path_data, show = False)

"""
Comentar que en los datos de este datasets viene una partición establecida para train y val. Sin embargo, la partición de 'val' no contempla clases Unseen. Por tanto no la vamos usar.
Crearemos una partición de validación para clases Seen y Unseen a partir de la partición de test. 
Como conjunto de entrenamiento usaremos el que viene dado por los índices de la variable 'trainval_loc' en att_splits. 
Los índices de las varaibles 'train_loc' y 'val_loc' no los vamos a usar.
"""
# Get the data from att_splits dictionary
allclasses_names            = att_splits['allclasses_names']
original_att                = att_splits['original_att'].T.astype('float')  # Attributos originales
attribute                   = att_splits['att'].T.astype('float')           # Atributos que no se de donde salen, pero son los que usan <=== IMPORTANTE
# Indixes of the instances in the train, test and validation sets
test_unseen_loc             = att_splits['test_unseen_loc'].squeeze() - 1
test_seen_loc               = att_splits['test_seen_loc'].squeeze() - 1
trainval_loc                = att_splits['trainval_loc'].squeeze() - 1      # En caso de no usar validación, aquí estara todo el entrenamiento
train_loc                   = att_splits['train_loc'].squeeze() - 1         # Esto es si usamos validacion, ver comentario arriba
val_loc                     = att_splits['val_loc'].squeeze() -1            # Esto es si usamos validacion, ver comentario arriba
# Get the dta from matcontent dictionary
feature =  matcontent['features'].T                       # Feature Matrix (Number of instances x Number of features)
labels  =  matcontent['labels'].astype(int).squeeze() - 1 # Ponemos que sea entero, eliminamos la dimension extra y con el '-1' movemos el rango de [1,200] a [0,199]

random.shuffle(trainval_loc)
# Es importante usar aquí la matrices feature y labels originales
trainval_feature = feature[trainval_loc]
trainval_labels  = labels[trainval_loc]
trainval_classes = np.unique(trainval_labels)
random.shuffle(trainval_classes)

classes_per_fold = int(trainval_classes.shape[0] / FOLDS)
acarreo          = trainval_classes.shape[0] % FOLDS


# Get attributes and preprocessing them
attribute = original_att if orig_attribute else attribute
attribute = scaler_data(get_scaler(scaler_str),attribute)




#################
##### FOLDS #####
#################
folds = []
for i in range(FOLDS):
    
    # Gather data for the fold
    start = i * classes_per_fold
    end   = (i + 1) * classes_per_fold if i != FOLDS - 1 else (i + 1) * classes_per_fold + acarreo
    
    fold_i_val_classes       = trainval_classes[start:end] # Unseen
    fold_i_training_classes  = [x for x in trainval_classes if x not in fold_i_val_classes] # Seen
    
    fold_i_val_loc           = np.where(np.isin(trainval_labels, fold_i_val_classes)) # index for val
    fold_i_training_loc      = np.where(np.isin(trainval_labels, fold_i_training_classes)) # Index for training
    # np.isin(element,test_element) Calculates element in test_elements, broadcasting over element only. 
    # #Returns a boolean array of the same shape as element that is True where an element of element is in 
    # #test_elements and False otherwise.
    # np.where(lists[bool]) returns the indexes of the True values in the lists
    
    assert np.intersect1d(fold_i_val_loc, fold_i_training_loc).shape[0] == 0, f"Error: Problems found in creating folds {i}. Val and training classes are not disjoint"
    assert np.intersect1d(fold_i_val_classes, fold_i_training_classes).shape[0] == 0, f"Error: Problems found in creating folds {i}. Val and training classes are not disjoint"
    assert all([i not in fold_i_training_classes for i in trainval_labels[fold_i_val_loc]]), f"Error: Problems found in creating folds {i}"
    assert all([i not in fold_i_val_classes for i in trainval_labels[fold_i_training_loc]]), f"Error: Problems found in creating folds {i}"

    fold_i_training_features = trainval_feature[fold_i_training_loc]
    fold_i_val_features      = trainval_feature[fold_i_val_loc]
    fold_i_training_labels   = trainval_labels[fold_i_training_loc]
    fold_i_val_labels        = trainval_labels[fold_i_val_loc]
    fold_i_ss_val            = gen_ss_from_data(fold_i_val_labels,attribute)
    fold_i_ss_training       = gen_ss_from_data(fold_i_training_labels,attribute)
    
    assert np.intersect1d(np.unique(fold_i_val_labels),np.unique(fold_i_training_labels)).shape[0] == 0, f"Los conjuntos del fold {i+1} de etiquetas no son disjuntos"
    
    # Preprocess the data
    fold_i_training_features, fold_i_val_features = scaler_data(get_scaler(scaler_str),
                                                                fold_i_training_features,
                                                                fold_i_val_features)
    
    # Creating Datasets 
    fold_training = Dataset(features = fold_i_training_features, 
                            labels   = fold_i_training_labels, 
                            att      = fold_i_ss_training, 
                            mode     = 'train')
    
    fold_val      = Dataset(features = fold_i_val_features,
                            labels   = fold_i_val_labels,
                            att      = fold_i_ss_val,
                            mode     = 'val')
    
    fold = StackedDataset({'train':fold_training, 'val':fold_val})
    
    folds.append(fold)
    
    if SHOW:
        print(f"Fold {i+1} || Val Classes {np.unique(fold_i_val_labels).shape} - {fold_i_val_labels.shape} instances || Training Classes {np.unique(fold_i_training_labels).shape} - {fold_i_training_labels.shape} instances")
        
        
        







args = Arguments('CUB',42,'rfe') # MODE = RFE
random.seed(args.seed)
np.random.seed(args.seed)
print(f"You've selected {args.dataset} dataset")
print(f"You've selected {args.mode} mode")
random_mode = False if args.mode == 'rfe' else True 
rfe_mode    = False if args.mode == 'random' else True

vattributes = np.arange(10, attribute.shape[1], step)
if attribute.shape[1] % step != 0:
    vattributes = np.append(vattributes, attribute.shape[1])

conteo          = np.zeros(attribute.shape[1])
best_folds_configuration = [] # Mejor configurración de atributos seleccionados en cada uno de los folds
for i, fold in enumerate(folds):

    print(f"Fold {i+1}...")

    training_data = fold.datasets['train']
    val_data      = fold.datasets['val']

    attributes_X_train = training_data.att.copy()

    rfe = RFE(estimator = None, estimator_name = 'SAE', n_features_to_select = 1, step = 1, verbose = True)
    rfe.fit(training_data.features, training_data.att,training_data.labels)
    ranking = rfe.get_ranking()
    
    fold_i_att_acc = {'Attributes': [],
                      'Train Acc': [],
                      'Val Acc': [],
                      'Mask':[]}
    
    for nv in vattributes:
        
        mask = ranking <= nv
        W = SAE(training_data.features.T, training_data.att[:,mask].T,500000) 
        # Training Acc
        gt_ss_training_adapted  = attribute[training_data.classes][:,mask]
        semantic_predicted = np.dot(training_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, training_data.classes,training_data.labels)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        # Val Acc
        gt_ss_val_adapted    = attribute[val_data.classes][:,mask]
        semantic_predicted = np.dot(val_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, val_data.classes,val_data.labels)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        # Save results
        fold_i_att_acc['Attributes'].append(nv)
        fold_i_att_acc['Train Acc'].append(zsl_accuracy_train)
        fold_i_att_acc['Val Acc'].append(zsl_accuracy1_unseen)
        fold_i_att_acc['Mask'].append(mask)
        
        if debug:
            print(f"nv: {nv} || Train: {zsl_accuracy_train} || Val: {zsl_accuracy1_unseen}")
    # Saving the best configuration of the fold
    fold_i_att_acc = pd.DataFrame(fold_i_att_acc).sort_values(by = 'Val Acc', ascending = False)
    best_folds_configuration.append(fold_i_att_acc.iloc[0])
    

for res in best_folds_configuration:
    conteo = conteo + np.asarray(res['Mask']).astype(int)
    
    
df = {}
for i in range(len(best_folds_configuration)):
    df[i] = best_folds_configuration[i].to_dict()
df = pd.DataFrame(df).T

if rfe_mode: 
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_rfe_train_val)
else:
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_random_val)
    
    
    
    
# Evaluamos en test 
test_results = {'Counts':[],'Attributes':[],'Train Acc':[],'Test Seen Acc':[],'Test Unseen Acc':[]}
j = 1
cadena = '5'
for i in range(FOLDS*2-1):
    if i < FOLDS:
        test_results['Counts'].append(str(FOLDS-i))
        test_results['Attributes'].append(np.where(conteo==FOLDS-i)[0].shape)
        mejores = np.where(conteo==FOLDS-i)[0]

    else:
        cadena = cadena+'-'+str(FOLDS-j)
        test_results['Counts'].append(cadena)
        test_results['Attributes'].append(np.where(conteo>=FOLDS-j)[0].shape)
        mejores = np.where(conteo>=FOLDS-j)[0]
        j+=1

    
    
    if mejores.shape[0] > 0:
        # Training
        training_feature = feature[trainval_loc]
        training_label   = labels[trainval_loc]
        ss_training      = gen_ss_from_data(training_label,attribute)
        # Get test
        test_unseen_feature = feature[test_unseen_loc]
        test_unseen_label   = labels[test_unseen_loc]
        ss_test_unseen      = gen_ss_from_data(test_unseen_label,attribute)
        test_seen_feature = feature[test_seen_loc]
        test_seen_label   = labels[test_seen_loc]
        ss_test_seen      = gen_ss_from_data(test_seen_label,attribute)
        # Preprocessing
        scaler = get_scaler(scaler_str)
        scaler.fit(training_feature)
        training_feature = scaler.transform(training_feature)
        test_unseen_feature = scaler.transform(test_unseen_feature)
        test_seen_feature = scaler.transform(test_seen_feature)
        # Fit the model
        W = SAE(training_feature.T, ss_training[:,mejores].T,500000) 
        gt_ss_training_adapted  = attribute[np.unique(training_label)][:,mejores]
        semantic_predicted = np.dot(training_feature, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, np.unique(training_label),training_label)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        test_results['Train Acc'].append(zsl_accuracy_train)
        # Evaluo en test seen
        gt_ss_val_adapted    = attribute[np.unique(test_seen_label)][:,mejores]
        semantic_predicted = np.dot(test_seen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_seen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_seen_label),test_seen_label)
        zsl_accuracy1_seen = round(zsl_accuracy1_seen,DECIMAL_NUMBERS)
        test_results['Test Seen Acc'].append(zsl_accuracy1_seen)
        # Evaluo en test unseen
        gt_ss_val_adapted    = attribute[np.unique(test_unseen_label)][:,mejores]
        semantic_predicted = np.dot(test_unseen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_unseen_label),test_unseen_label)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        test_results['Test Unseen Acc'].append(zsl_accuracy1_unseen)
    else:
        test_results['Train Acc'].append(0)
        test_results['Test Seen Acc'].append(0)
        test_results['Test Unseen Acc'].append(0)
    
if rfe_mode:
    pd.DataFrame(test_results).to_csv(path_oracle_rfe_train_val)
else:
    pd.DataFrame(test_results).to_csv(path_oracle_random_val)
    
pd.DataFrame(test_results)

You've selected CUB dataset
You've selected rfe mode
Fold 1 || Val Classes (30,) - (1400,) instances || Training Classes (120,) - (5657,) instances
Fold 2 || Val Classes (30,) - (1465,) instances || Training Classes (120,) - (5592,) instances
Fold 3 || Val Classes (30,) - (1386,) instances || Training Classes (120,) - (5671,) instances
Fold 4 || Val Classes (30,) - (1406,) instances || Training Classes (120,) - (5651,) instances
Fold 5 || Val Classes (30,) - (1400,) instances || Training Classes (120,) - (5657,) instances
You've selected CUB dataset
You've selected rfe mode
Fold 1...
Ranking: [79, 17, 39, 167, 105, 197, 120, 24, 112, 9, 58, 248, 285, 32, 66, 256, 207, 115, 268, 118, 235, 273, 286, 52, 210, 49, 175, 102, 8, 278, 233, 282, 31, 87, 95, 77, 182, 261, 133, 185, 296, 127, 18, 16, 155, 89, 204, 65, 106, 172, 293, 161, 33, 6, 258, 152, 290, 114, 291, 222, 276, 302, 287, 40, 190, 164, 198, 148, 205, 121, 275, 47, 110, 100, 22, 232, 70, 231, 265, 186, 46, 109, 220, 272, 260, 267, 73, 180, 128, 304, 64, 129, 169, 230, 229, 143, 34, 98, 305, 4, 117, 82, 92, 61, 189, 68, 75, 163, 307, 221, 288, 280, 125, 243, 28, 202, 44, 193, 181, 270, 42, 191, 151, 271, 84, 218, 289, 176, 101, 19, 30, 141, 63, 146, 150, 43, 37, 94, 226, 217, 255, 149, 194, 300, 113, 213, 51, 166, 279, 48, 134, 55, 130, 281, 38, 227, 86, 15, 14, 219, 3, 177, 72, 234, 88, 156, 137, 262, 269, 212, 209, 174, 277, 93, 36, 159, 301, 74, 160, 91, 131, 309, 195, 179, 144, 224, 78, 81, 251, 62, 266, 228, 214, 183, 247, 57, 132, 5, 188, 178, 104, 297, 274, 41, 124, 201, 147, 139, 244, 158, 157, 162, 23, 292, 136, 1, 103, 35, 257, 240, 245, 215, 249, 123, 20, 263, 264, 142, 170, 59, 27, 200, 303, 138, 111, 196, 238, 284, 90, 306, 29, 242, 283, 154, 192, 126, 250, 60, 168, 254, 311, 10, 295, 140, 71, 135, 85, 67, 69, 187, 252, 26, 206, 12, 83, 310, 246, 50, 173, 0, 107, 25, 236, 45, 171, 237, 97, 76, 165, 199, 294, 216, 122, 54, 13, 308, 203, 145, 153, 225, 11, 7, 96, 298, 239, 116, 184, 108, 299, 208, 211, 80, 2, 223, 259, 99, 56, 241, 53, 21, 119, 253]
nv: 10 || Train: 48.542 || Val: 20.143
nv: 15 || Train: 68.853 || Val: 24.429
nv: 20 || Train: 74.739 || Val: 25.786
nv: 25 || Train: 83.631 || Val: 28.571
nv: 30 || Train: 87.361 || Val: 32.143
nv: 35 || Train: 88.156 || Val: 35.714
nv: 40 || Train: 90.101 || Val: 36.071
nv: 45 || Train: 91.904 || Val: 38.357
nv: 50 || Train: 92.77 || Val: 40.0
nv: 55 || Train: 93.353 || Val: 41.214
nv: 60 || Train: 93.689 || Val: 41.143
nv: 65 || Train: 94.167 || Val: 42.643
nv: 70 || Train: 94.52 || Val: 42.714
nv: 75 || Train: 94.432 || Val: 43.643
nv: 80 || Train: 94.838 || Val: 43.429
nv: 85 || Train: 95.156 || Val: 44.714
nv: 90 || Train: 94.856 || Val: 44.143
nv: 95 || Train: 95.156 || Val: 45.357
nv: 100 || Train: 95.316 || Val: 46.857
nv: 105 || Train: 95.386 || Val: 46.286
nv: 110 || Train: 95.404 || Val: 45.714
nv: 115 || Train: 95.651 || Val: 45.857
nv: 120 || Train: 96.058 || Val: 45.857
nv: 125 || Train: 96.111 || Val: 46.786
nv: 130 || Train: 96.323 || Val: 47.429
nv: 135 || Train: 96.076 || Val: 47.571
nv: 140 || Train: 96.182 || Val: 47.786
nv: 145 || Train: 96.217 || Val: 47.571
nv: 150 || Train: 96.27 || Val: 47.857
nv: 155 || Train: 96.341 || Val: 49.286
nv: 160 || Train: 96.341 || Val: 49.143
nv: 165 || Train: 96.358 || Val: 49.071
nv: 170 || Train: 96.394 || Val: 49.429
nv: 175 || Train: 96.376 || Val: 48.857
nv: 180 || Train: 96.288 || Val: 48.786
nv: 185 || Train: 96.358 || Val: 48.286
nv: 190 || Train: 96.076 || Val: 47.643
nv: 195 || Train: 96.252 || Val: 46.857
nv: 200 || Train: 96.447 || Val: 48.429
nv: 205 || Train: 96.341 || Val: 48.714
nv: 210 || Train: 96.199 || Val: 48.071
nv: 215 || Train: 96.252 || Val: 48.071
nv: 220 || Train: 96.482 || Val: 48.429
nv: 225 || Train: 96.447 || Val: 49.286
nv: 230 || Train: 96.412 || Val: 48.643
nv: 235 || Train: 96.394 || Val: 49.071
nv: 240 || Train: 96.447 || Val: 49.929
nv: 245 || Train: 96.482 || Val: 50.286
nv: 250 || Train: 96.535 || Val: 50.786
nv: 255 || Train: 96.482 || Val: 51.143
nv: 260 || Train: 96.465 || Val: 51.643
nv: 265 || Train: 96.535 || Val: 51.429
nv: 270 || Train: 96.553 || Val: 51.571
nv: 275 || Train: 96.606 || Val: 51.643
nv: 280 || Train: 96.747 || Val: 51.071
nv: 285 || Train: 96.73 || Val: 50.857
nv: 290 || Train: 96.694 || Val: 51.786
nv: 295 || Train: 96.765 || Val: 51.643
nv: 300 || Train: 96.747 || Val: 50.929
nv: 305 || Train: 96.8 || Val: 51.0
nv: 310 || Train: 96.889 || Val: 51.429
nv: 312 || Train: 96.836 || Val: 51.214
Fold 2...
Ranking: [269, 290, 275, 268, 277, 171, 118, 287, 52, 210, 77, 74, 120, 114, 62, 39, 180, 235, 92, 169, 197, 105, 4, 214, 24, 58, 248, 13, 79, 172, 37, 167, 38, 28, 292, 22, 83, 296, 103, 233, 71, 9, 241, 174, 155, 273, 47, 278, 218, 72, 286, 262, 222, 217, 261, 78, 61, 75, 182, 307, 196, 251, 181, 276, 305, 115, 281, 112, 274, 271, 309, 63, 234, 302, 267, 6, 14, 23, 207, 130, 206, 220, 215, 143, 93, 176, 84, 208, 76, 219, 53, 21, 150, 102, 256, 205, 195, 124, 3, 49, 129, 272, 265, 81, 119, 239, 15, 285, 68, 211, 204, 89, 109, 12, 29, 113, 166, 11, 139, 178, 283, 94, 161, 17, 157, 247, 240, 226, 293, 156, 1, 123, 86, 101, 284, 85, 99, 212, 146, 237, 95, 57, 192, 253, 190, 98, 10, 152, 66, 56, 73, 141, 223, 246, 227, 225, 8, 306, 291, 151, 50, 200, 228, 201, 137, 164, 43, 144, 26, 32, 5, 252, 87, 88, 185, 259, 232, 128, 116, 46, 70, 41, 238, 132, 97, 148, 258, 311, 199, 42, 229, 257, 67, 55, 18, 82, 162, 147, 133, 191, 33, 177, 245, 221, 298, 25, 194, 80, 231, 224, 175, 295, 255, 138, 122, 48, 213, 270, 243, 310, 0, 168, 149, 60, 165, 280, 142, 183, 135, 188, 266, 36, 126, 242, 288, 34, 131, 64, 145, 230, 108, 69, 90, 134, 30, 107, 154, 249, 184, 289, 202, 203, 159, 308, 264, 160, 136, 187, 263, 104, 110, 111, 179, 91, 45, 20, 2, 209, 279, 51, 16, 299, 40, 27, 158, 170, 31, 125, 186, 44, 35, 19, 96, 100, 216, 244, 121, 189, 198, 117, 153, 303, 282, 304, 294, 106, 254, 54, 7, 300, 140, 250, 173, 236, 65, 260, 127, 297, 193, 59, 163, 301]
nv: 10 || Train: 47.318 || Val: 14.881
nv: 15 || Train: 68.777 || Val: 19.044
nv: 20 || Train: 76.699 || Val: 17.133
nv: 25 || Train: 83.691 || Val: 21.706
nv: 30 || Train: 88.358 || Val: 25.256
nv: 35 || Train: 89.664 || Val: 26.485
nv: 40 || Train: 90.826 || Val: 28.601
nv: 45 || Train: 93.222 || Val: 29.147
nv: 50 || Train: 93.205 || Val: 30.922
nv: 55 || Train: 93.705 || Val: 33.106
nv: 60 || Train: 94.099 || Val: 34.881
nv: 65 || Train: 94.349 || Val: 37.201
nv: 70 || Train: 94.474 || Val: 37.543
nv: 75 || Train: 94.957 || Val: 38.703
nv: 80 || Train: 95.136 || Val: 38.771
nv: 85 || Train: 95.279 || Val: 37.952
nv: 90 || Train: 95.422 || Val: 39.113
nv: 95 || Train: 95.815 || Val: 40.273
nv: 100 || Train: 95.959 || Val: 39.727
nv: 105 || Train: 95.851 || Val: 41.297
nv: 110 || Train: 95.887 || Val: 41.57
nv: 115 || Train: 95.887 || Val: 41.024
nv: 120 || Train: 96.28 || Val: 40.341
nv: 125 || Train: 96.28 || Val: 40.0
nv: 130 || Train: 96.531 || Val: 41.092
nv: 135 || Train: 96.584 || Val: 41.775
nv: 140 || Train: 96.745 || Val: 42.389
nv: 145 || Train: 96.835 || Val: 42.73
nv: 150 || Train: 96.799 || Val: 43.208
nv: 155 || Train: 96.871 || Val: 44.027
nv: 160 || Train: 96.799 || Val: 43.413
nv: 165 || Train: 96.978 || Val: 43.959
nv: 170 || Train: 96.942 || Val: 43.959
nv: 175 || Train: 97.014 || Val: 44.642
nv: 180 || Train: 96.96 || Val: 44.915
nv: 185 || Train: 96.871 || Val: 43.618
nv: 190 || Train: 96.853 || Val: 43.959
nv: 195 || Train: 96.888 || Val: 44.027
nv: 200 || Train: 96.942 || Val: 44.096
nv: 205 || Train: 97.031 || Val: 44.369
nv: 210 || Train: 97.157 || Val: 44.71
nv: 215 || Train: 97.192 || Val: 44.642
nv: 220 || Train: 97.192 || Val: 45.461
nv: 225 || Train: 97.157 || Val: 45.802
nv: 230 || Train: 97.139 || Val: 45.529
nv: 235 || Train: 97.157 || Val: 45.666
nv: 240 || Train: 97.085 || Val: 44.71
nv: 245 || Train: 97.246 || Val: 45.256
nv: 250 || Train: 97.228 || Val: 45.392
nv: 255 || Train: 97.228 || Val: 44.778
nv: 260 || Train: 97.3 || Val: 45.051
nv: 265 || Train: 97.318 || Val: 45.324
nv: 270 || Train: 97.425 || Val: 46.007
nv: 275 || Train: 97.425 || Val: 46.007
nv: 280 || Train: 97.461 || Val: 46.143
nv: 285 || Train: 97.335 || Val: 45.597
nv: 290 || Train: 97.389 || Val: 45.597
nv: 295 || Train: 97.371 || Val: 46.348
nv: 300 || Train: 97.246 || Val: 45.802
nv: 305 || Train: 97.264 || Val: 46.212
nv: 310 || Train: 97.246 || Val: 46.348
nv: 312 || Train: 97.246 || Val: 46.485
Fold 3...
Ranking: [118, 210, 52, 28, 17, 286, 32, 276, 268, 39, 197, 22, 290, 92, 180, 261, 77, 133, 235, 296, 13, 109, 79, 105, 120, 285, 89, 37, 167, 9, 83, 155, 24, 66, 4, 58, 223, 248, 269, 75, 207, 74, 100, 171, 305, 103, 185, 277, 151, 256, 218, 149, 280, 114, 222, 6, 43, 233, 278, 220, 231, 215, 143, 190, 252, 18, 172, 239, 214, 31, 178, 292, 76, 275, 251, 62, 72, 271, 265, 137, 19, 110, 64, 201, 68, 258, 164, 234, 125, 121, 245, 38, 115, 65, 198, 229, 259, 55, 102, 232, 49, 200, 142, 16, 71, 262, 169, 90, 14, 108, 212, 94, 176, 263, 106, 217, 61, 47, 144, 273, 40, 35, 96, 93, 141, 67, 30, 129, 95, 82, 148, 311, 181, 297, 287, 145, 87, 175, 241, 12, 227, 237, 29, 196, 88, 20, 302, 42, 219, 147, 161, 34, 309, 84, 101, 81, 194, 221, 157, 104, 10, 23, 205, 78, 112, 63, 188, 208, 53, 230, 140, 113, 44, 289, 270, 244, 86, 189, 162, 183, 15, 177, 69, 124, 182, 240, 70, 91, 163, 116, 267, 150, 1, 36, 282, 266, 119, 193, 25, 274, 306, 128, 279, 135, 203, 73, 238, 250, 54, 170, 264, 7, 246, 283, 97, 301, 8, 300, 291, 249, 179, 186, 139, 199, 247, 98, 298, 260, 173, 187, 3, 136, 294, 45, 41, 134, 50, 295, 304, 204, 159, 225, 307, 243, 184, 224, 122, 195, 48, 2, 192, 191, 126, 213, 228, 303, 202, 156, 209, 80, 51, 146, 211, 27, 57, 308, 132, 160, 166, 174, 60, 56, 255, 257, 288, 206, 59, 158, 127, 152, 153, 154, 99, 293, 107, 131, 46, 85, 130, 299, 281, 138, 21, 11, 216, 226, 33, 310, 123, 0, 26, 242, 117, 5, 165, 236, 111, 284, 272, 254, 168, 253]
nv: 10 || Train: 52.566 || Val: 26.768
nv: 15 || Train: 66.937 || Val: 34.199
nv: 20 || Train: 75.577 || Val: 40.476
nv: 25 || Train: 80.427 || Val: 41.342
nv: 30 || Train: 82.666 || Val: 40.693
nv: 35 || Train: 86.934 || Val: 41.991
nv: 40 || Train: 87.674 || Val: 42.569
nv: 45 || Train: 89.332 || Val: 44.805
nv: 50 || Train: 91.218 || Val: 46.753
nv: 55 || Train: 91.377 || Val: 46.681
nv: 60 || Train: 92.664 || Val: 48.701
nv: 65 || Train: 93.299 || Val: 48.918
nv: 70 || Train: 93.687 || Val: 49.206
nv: 75 || Train: 94.163 || Val: 50.289
nv: 80 || Train: 93.758 || Val: 50.216
nv: 85 || Train: 94.022 || Val: 47.98
nv: 90 || Train: 94.287 || Val: 47.619
nv: 95 || Train: 94.41 || Val: 48.629
nv: 100 || Train: 94.798 || Val: 49.134
nv: 105 || Train: 94.675 || Val: 49.206
nv: 110 || Train: 94.922 || Val: 49.206
nv: 115 || Train: 94.78 || Val: 49.278
nv: 120 || Train: 94.78 || Val: 50.722
nv: 125 || Train: 95.08 || Val: 51.01
nv: 130 || Train: 95.063 || Val: 51.732
nv: 135 || Train: 95.168 || Val: 51.948
nv: 140 || Train: 95.309 || Val: 52.67
nv: 145 || Train: 95.521 || Val: 52.092
nv: 150 || Train: 95.68 || Val: 52.237
nv: 155 || Train: 95.627 || Val: 52.958
nv: 160 || Train: 95.821 || Val: 52.886
nv: 165 || Train: 95.645 || Val: 53.03
nv: 170 || Train: 95.75 || Val: 53.175
nv: 175 || Train: 95.786 || Val: 53.102
nv: 180 || Train: 95.609 || Val: 53.896
nv: 185 || Train: 95.574 || Val: 53.535
nv: 190 || Train: 95.733 || Val: 54.04
nv: 195 || Train: 95.715 || Val: 53.319
nv: 200 || Train: 95.856 || Val: 54.401
nv: 205 || Train: 95.856 || Val: 54.185
nv: 210 || Train: 96.367 || Val: 54.906
nv: 215 || Train: 96.456 || Val: 54.834
nv: 220 || Train: 96.403 || Val: 54.113
nv: 225 || Train: 96.473 || Val: 54.762
nv: 230 || Train: 96.491 || Val: 54.545
nv: 235 || Train: 96.561 || Val: 55.7
nv: 240 || Train: 96.561 || Val: 54.978
nv: 245 || Train: 96.597 || Val: 54.329
nv: 250 || Train: 96.614 || Val: 55.339
nv: 255 || Train: 96.65 || Val: 55.7
nv: 260 || Train: 96.72 || Val: 56.566
nv: 265 || Train: 96.808 || Val: 56.638
nv: 270 || Train: 96.773 || Val: 57.431
nv: 275 || Train: 96.755 || Val: 56.421
nv: 280 || Train: 96.844 || Val: 56.349
nv: 285 || Train: 96.826 || Val: 56.421
nv: 290 || Train: 96.879 || Val: 56.926
nv: 295 || Train: 96.879 || Val: 57.287
nv: 300 || Train: 96.879 || Val: 57.431
nv: 305 || Train: 96.949 || Val: 57.648
nv: 310 || Train: 97.02 || Val: 58.081
nv: 312 || Train: 97.073 || Val: 57.864
Fold 4...
Ranking: [269, 287, 276, 268, 273, 286, 210, 22, 6, 17, 118, 105, 52, 83, 92, 28, 77, 235, 39, 79, 261, 133, 120, 197, 37, 13, 277, 67, 285, 171, 180, 32, 167, 24, 136, 4, 129, 283, 95, 274, 248, 58, 290, 66, 242, 61, 305, 222, 292, 172, 112, 9, 109, 42, 185, 259, 243, 246, 178, 74, 296, 150, 244, 103, 256, 310, 207, 114, 282, 213, 169, 212, 151, 62, 54, 108, 8, 71, 116, 267, 220, 218, 234, 260, 161, 57, 50, 56, 115, 31, 230, 3, 200, 75, 208, 143, 134, 247, 43, 89, 223, 302, 265, 219, 163, 275, 175, 252, 280, 88, 117, 291, 147, 141, 182, 155, 227, 49, 233, 209, 146, 217, 149, 142, 73, 90, 64, 2, 190, 206, 16, 100, 145, 87, 139, 194, 65, 72, 297, 263, 229, 224, 78, 201, 164, 183, 221, 30, 306, 308, 137, 82, 165, 51, 110, 63, 47, 288, 69, 215, 125, 205, 131, 68, 281, 168, 270, 48, 101, 307, 26, 144, 84, 38, 191, 228, 294, 148, 70, 12, 119, 271, 35, 195, 91, 158, 179, 121, 186, 7, 19, 298, 130, 189, 264, 21, 94, 157, 20, 257, 293, 295, 211, 236, 128, 237, 123, 173, 14, 226, 278, 97, 311, 193, 127, 154, 258, 135, 113, 102, 188, 262, 284, 152, 98, 34, 174, 204, 241, 156, 216, 203, 289, 11, 44, 27, 250, 232, 126, 36, 140, 153, 251, 303, 231, 214, 253, 132, 124, 138, 245, 33, 196, 170, 202, 187, 304, 99, 299, 53, 96, 266, 239, 272, 249, 86, 10, 301, 45, 199, 122, 255, 29, 40, 159, 59, 225, 25, 80, 279, 0, 106, 41, 192, 1, 46, 18, 15, 85, 60, 166, 5, 23, 240, 300, 181, 93, 254, 309, 160, 107, 184, 176, 198, 162, 76, 238, 55, 111, 104, 81, 177]
nv: 10 || Train: 56.521 || Val: 16.003
nv: 15 || Train: 73.598 || Val: 21.622
nv: 20 || Train: 79.083 || Val: 27.027
nv: 25 || Train: 84.286 || Val: 31.223
nv: 30 || Train: 88.055 || Val: 36.131
nv: 35 || Train: 88.445 || Val: 36.984
nv: 40 || Train: 90.55 || Val: 38.265
nv: 45 || Train: 92.55 || Val: 39.26
nv: 50 || Train: 92.762 || Val: 38.905
nv: 55 || Train: 92.851 || Val: 41.252
nv: 60 || Train: 93.913 || Val: 39.972
nv: 65 || Train: 94.833 || Val: 41.394
nv: 70 || Train: 94.886 || Val: 41.679
nv: 75 || Train: 95.275 || Val: 41.038
nv: 80 || Train: 95.328 || Val: 41.679
nv: 85 || Train: 95.948 || Val: 42.532
nv: 90 || Train: 96.39 || Val: 43.741
nv: 95 || Train: 96.195 || Val: 44.95
nv: 100 || Train: 96.001 || Val: 45.306
nv: 105 || Train: 96.337 || Val: 46.088
nv: 110 || Train: 96.762 || Val: 46.515
nv: 115 || Train: 96.956 || Val: 46.159
nv: 120 || Train: 97.116 || Val: 46.728
nv: 125 || Train: 97.116 || Val: 46.515
nv: 130 || Train: 97.186 || Val: 45.661
nv: 135 || Train: 97.416 || Val: 45.804
nv: 140 || Train: 97.275 || Val: 46.302
nv: 145 || Train: 97.328 || Val: 46.728
nv: 150 || Train: 97.293 || Val: 46.23
nv: 155 || Train: 97.363 || Val: 46.23
nv: 160 || Train: 97.328 || Val: 46.515
nv: 165 || Train: 97.346 || Val: 47.013
nv: 170 || Train: 97.293 || Val: 46.657
nv: 175 || Train: 97.346 || Val: 47.653
nv: 180 || Train: 97.363 || Val: 47.582
nv: 185 || Train: 97.399 || Val: 48.151
nv: 190 || Train: 97.293 || Val: 47.866
nv: 195 || Train: 97.328 || Val: 47.937
nv: 200 || Train: 97.275 || Val: 48.009
nv: 205 || Train: 97.31 || Val: 48.151
nv: 210 || Train: 97.239 || Val: 48.649
nv: 215 || Train: 97.328 || Val: 48.791
nv: 220 || Train: 97.293 || Val: 48.435
nv: 225 || Train: 97.328 || Val: 48.293
nv: 230 || Train: 97.469 || Val: 47.866
nv: 235 || Train: 97.469 || Val: 48.009
nv: 240 || Train: 97.452 || Val: 48.862
nv: 245 || Train: 97.434 || Val: 48.862
nv: 250 || Train: 97.452 || Val: 49.218
nv: 255 || Train: 97.434 || Val: 48.933
nv: 260 || Train: 97.416 || Val: 48.72
nv: 265 || Train: 97.487 || Val: 48.933
nv: 270 || Train: 97.558 || Val: 49.075
nv: 275 || Train: 97.611 || Val: 47.937
nv: 280 || Train: 97.646 || Val: 48.009
nv: 285 || Train: 97.7 || Val: 48.435
nv: 290 || Train: 97.859 || Val: 49.218
nv: 295 || Train: 97.806 || Val: 48.862
nv: 300 || Train: 97.735 || Val: 48.435
nv: 305 || Train: 97.717 || Val: 48.933
nv: 310 || Train: 97.717 || Val: 48.293
nv: 312 || Train: 97.77 || Val: 48.435
Fold 5...
Ranking: [269, 17, 39, 32, 197, 118, 28, 105, 210, 9, 66, 52, 22, 286, 167, 24, 207, 290, 61, 180, 79, 13, 100, 58, 112, 265, 248, 256, 31, 74, 120, 233, 92, 223, 87, 285, 276, 37, 65, 235, 115, 261, 125, 16, 204, 305, 47, 268, 49, 171, 83, 222, 110, 89, 218, 68, 133, 275, 64, 4, 12, 175, 44, 46, 109, 278, 208, 258, 30, 205, 277, 201, 287, 76, 103, 288, 6, 173, 274, 62, 259, 273, 255, 202, 190, 219, 226, 27, 178, 19, 252, 95, 121, 220, 183, 90, 71, 270, 86, 116, 35, 182, 198, 189, 69, 34, 50, 234, 292, 138, 232, 8, 147, 176, 113, 43, 2, 168, 102, 40, 15, 170, 266, 229, 91, 114, 239, 106, 78, 253, 70, 206, 217, 307, 164, 185, 249, 99, 57, 172, 296, 18, 231, 59, 127, 184, 20, 221, 293, 284, 85, 250, 179, 80, 186, 294, 310, 48, 199, 128, 174, 137, 152, 214, 139, 151, 154, 260, 11, 107, 271, 60, 227, 73, 257, 77, 309, 88, 297, 143, 129, 300, 200, 10, 177, 264, 194, 153, 75, 1, 98, 25, 245, 161, 262, 311, 124, 145, 230, 29, 211, 155, 136, 141, 280, 242, 134, 119, 104, 192, 224, 237, 238, 295, 272, 240, 81, 56, 281, 36, 213, 166, 267, 0, 157, 187, 33, 301, 263, 149, 254, 243, 51, 140, 97, 130, 279, 291, 55, 41, 82, 289, 216, 117, 94, 126, 132, 241, 163, 308, 38, 72, 123, 225, 144, 228, 150, 26, 63, 84, 196, 159, 193, 53, 236, 162, 303, 146, 203, 158, 304, 135, 209, 45, 5, 54, 215, 247, 306, 165, 142, 122, 195, 131, 282, 188, 14, 160, 101, 3, 148, 181, 298, 111, 246, 156, 67, 108, 7, 93, 302, 169, 21, 251, 23, 244, 283, 299, 212, 191, 42, 96]
nv: 10 || Train: 64.716 || Val: 29.214
nv: 15 || Train: 73.608 || Val: 29.214
nv: 20 || Train: 80.52 || Val: 34.143
nv: 25 || Train: 84.78 || Val: 34.929
nv: 30 || Train: 86.76 || Val: 35.0
nv: 35 || Train: 88.74 || Val: 38.714
nv: 40 || Train: 90.207 || Val: 39.929
nv: 45 || Train: 91.603 || Val: 42.571
nv: 50 || Train: 92.54 || Val: 44.214
nv: 55 || Train: 93.053 || Val: 44.286
nv: 60 || Train: 93.353 || Val: 43.857
nv: 65 || Train: 93.512 || Val: 43.286
nv: 70 || Train: 93.53 || Val: 44.071
nv: 75 || Train: 93.654 || Val: 45.429
nv: 80 || Train: 93.707 || Val: 44.571
nv: 85 || Train: 94.184 || Val: 45.5
nv: 90 || Train: 94.608 || Val: 46.714
nv: 95 || Train: 94.555 || Val: 46.214
nv: 100 || Train: 94.715 || Val: 47.143
nv: 105 || Train: 94.821 || Val: 47.786
nv: 110 || Train: 94.785 || Val: 47.143
nv: 115 || Train: 94.856 || Val: 47.071
nv: 120 || Train: 94.927 || Val: 49.286
nv: 125 || Train: 95.121 || Val: 48.571
nv: 130 || Train: 95.316 || Val: 48.143
nv: 135 || Train: 95.298 || Val: 47.643
nv: 140 || Train: 95.704 || Val: 48.214
nv: 145 || Train: 95.757 || Val: 48.429
nv: 150 || Train: 95.864 || Val: 48.071
nv: 155 || Train: 95.934 || Val: 48.429
nv: 160 || Train: 96.146 || Val: 48.643
nv: 165 || Train: 96.252 || Val: 48.143
nv: 170 || Train: 96.235 || Val: 47.286
nv: 175 || Train: 96.27 || Val: 46.714
nv: 180 || Train: 96.341 || Val: 46.929
nv: 185 || Train: 96.394 || Val: 48.071
nv: 190 || Train: 96.465 || Val: 48.071
nv: 195 || Train: 96.447 || Val: 48.857
nv: 200 || Train: 96.27 || Val: 48.929
nv: 205 || Train: 96.412 || Val: 49.214
nv: 210 || Train: 96.412 || Val: 49.143
nv: 215 || Train: 96.518 || Val: 49.571
nv: 220 || Train: 96.341 || Val: 49.643
nv: 225 || Train: 96.288 || Val: 50.286
nv: 230 || Train: 96.518 || Val: 49.143
nv: 235 || Train: 96.535 || Val: 48.857
nv: 240 || Train: 96.624 || Val: 48.929
nv: 245 || Train: 96.677 || Val: 48.714
nv: 250 || Train: 96.765 || Val: 48.429
nv: 255 || Train: 96.836 || Val: 48.786
nv: 260 || Train: 96.836 || Val: 48.714
nv: 265 || Train: 96.889 || Val: 48.143
nv: 270 || Train: 96.96 || Val: 48.071
nv: 275 || Train: 97.03 || Val: 48.071
nv: 280 || Train: 96.924 || Val: 48.143
nv: 285 || Train: 96.977 || Val: 48.071
nv: 290 || Train: 96.96 || Val: 48.5

      Counts Attributes  Train Acc  Test Seen Acc  Test Unseen Acc
0          5     (164,)     91.937         57.993           41.052
1          4     (130,)     91.668         57.426           36.131
2          3      (15,)     61.046         26.474           19.077
3          2       (3,)      6.334          3.231            4.988
4          1       (0,)      0.000          0.000            0.000
5        5-4     (294,)     93.297         60.658           41.658
6      5-4-3     (309,)     93.439         60.998           41.827
7    5-4-3-2     (312,)     93.411         60.941           41.692
8  5-4-3-2-1     (312,)     93.411         60.941           41.692

# CUB - Val Val

In [3]:
args = Arguments('CUB',42,'rfe') # MODE = RFE


random.seed(args.seed)
np.random.seed(args.seed)
print(f"You've selected {args.dataset} dataset")
print(f"You've selected {args.mode} mode")
random_mode = False if args.mode == 'rfe' else True 
rfe_mode    = False if args.mode == 'random' else True




vattributes = np.arange(10, attribute.shape[1], step)
if attribute.shape[1] % step != 0:
    vattributes = np.append(vattributes, attribute.shape[1])

conteo          = np.zeros(attribute.shape[1])
best_folds_configuration = [] # Mejor configurración de atributos seleccionados en cada uno de los folds
for i, fold in enumerate(folds):

    print(f"Fold {i+1}...")

    training_data = fold.datasets['train']
    val_data      = fold.datasets['val']



    rfe = RFE(estimator = None, estimator_name = 'SAE', n_features_to_select = 1, step = 1, verbose = True)
    rfe.fit(val_data.features, val_data.att,val_data.labels)
    ranking = rfe.get_ranking()
    
    fold_i_att_acc = {'Attributes': [],
                      'Train Acc': [],
                      'Val Acc': [],
                      'Mask':[]}
    
    for nv in vattributes:
        
        mask = ranking <= nv
        W = SAE(training_data.features.T, training_data.att[:,mask].T,500000) 
        # Training Acc
        gt_ss_training_adapted  = attribute[training_data.classes][:,mask]
        semantic_predicted = np.dot(training_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, training_data.classes,training_data.labels)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        # Val Acc
        gt_ss_val_adapted    = attribute[val_data.classes][:,mask]
        semantic_predicted = np.dot(val_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, val_data.classes,val_data.labels)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        # Save results
        fold_i_att_acc['Attributes'].append(nv)
        fold_i_att_acc['Train Acc'].append(zsl_accuracy_train)
        fold_i_att_acc['Val Acc'].append(zsl_accuracy1_unseen)
        fold_i_att_acc['Mask'].append(mask)
        
        if debug:
            print(f"nv: {nv} || Train: {zsl_accuracy_train} || Val: {zsl_accuracy1_unseen}")
    # Saving the best configuration of the fold
    fold_i_att_acc = pd.DataFrame(fold_i_att_acc).sort_values(by = 'Val Acc', ascending = False)
    best_folds_configuration.append(fold_i_att_acc.iloc[0])
    

for res in best_folds_configuration:
    conteo = conteo + np.asarray(res['Mask']).astype(int)
   
   
   
   
df = {}
for i in range(len(best_folds_configuration)):
    df[i] = best_folds_configuration[i].to_dict()
df = pd.DataFrame(df).T

if rfe_mode: # Los mejores resultados de cada fold y el conteo
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_rfe_val_val)
else:
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_random_val)
    
    
    
    
    
    
    
    
# Evaluamos en test 
test_results = {'Counts':[],'Attributes':[],'Train Acc':[],'Test Seen Acc':[],'Test Unseen Acc':[]}
j = 1
cadena = '5'
for i in range(FOLDS*2-1):
    if i < FOLDS:
        test_results['Counts'].append(str(FOLDS-i))
        test_results['Attributes'].append(np.where(conteo==FOLDS-i)[0].shape)
        mejores = np.where(conteo==FOLDS-i)[0]
        print(FOLDS-i)
    else:
        cadena = cadena+'-'+str(FOLDS-j)
        test_results['Counts'].append(cadena)
        test_results['Attributes'].append(np.where(conteo>=FOLDS-j)[0].shape)
        mejores = np.where(conteo>=FOLDS-j)[0]
        j+=1
        print(FOLDS-j)
    
    
    if mejores.shape[0] > 0:
        # Training
        training_feature = feature[trainval_loc].copy()
        training_label   = labels[trainval_loc].copy()
        ss_training      = gen_ss_from_data(training_label,attribute)
        # Get test
        test_unseen_feature = feature[test_unseen_loc].copy()
        test_unseen_label   = labels[test_unseen_loc].copy()
        ss_test_unseen      = gen_ss_from_data(test_unseen_label,attribute)
        test_seen_feature = feature[test_seen_loc].copy()
        test_seen_label   = labels[test_seen_loc].copy()
        ss_test_seen      = gen_ss_from_data(test_seen_label,attribute)
        # Preprocessing
        scaler = get_scaler(scaler_str)
        scaler.fit(training_feature)
        training_feature = scaler.transform(training_feature)
        test_unseen_feature = scaler.transform(test_unseen_feature)
        test_seen_feature = scaler.transform(test_seen_feature)
        # Fit the model
        W = SAE(training_feature.T, ss_training[:,mejores].T,500000) 
        gt_ss_training_adapted  = attribute[np.unique(training_label)][:,mejores]
        semantic_predicted = np.dot(training_feature, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, np.unique(training_label),training_label)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        test_results['Train Acc'].append(zsl_accuracy_train)
        # Evaluo en test seen
        gt_ss_val_adapted    = attribute[np.unique(test_seen_label)][:,mejores]
        semantic_predicted = np.dot(test_seen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_seen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_seen_label),test_seen_label)
        zsl_accuracy1_seen = round(zsl_accuracy1_seen,DECIMAL_NUMBERS)
        test_results['Test Seen Acc'].append(zsl_accuracy1_seen)
        # Evaluo en test unseen
        gt_ss_val_adapted    = attribute[np.unique(test_unseen_label)][:,mejores]
        semantic_predicted = np.dot(test_unseen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_unseen_label),test_unseen_label)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        test_results['Test Unseen Acc'].append(zsl_accuracy1_unseen)
    else:
        test_results['Train Acc'].append(0)
        test_results['Test Seen Acc'].append(0)
        test_results['Test Unseen Acc'].append(0)
    
if rfe_mode:
    pd.DataFrame(test_results).to_csv(path_oracle_rfe_val_val)
else:
    pd.DataFrame(test_results).to_csv(path_oracle_random_val)
    
pd.DataFrame(test_results)

You've selected CUB dataset
You've selected rfe mode
Fold 1...
Ranking: [271, 276, 110, 292, 187, 154, 299, 104, 81, 28, 307, 60, 164, 117, 157, 64, 149, 21, 294, 111, 237, 304, 226, 199, 241, 166, 219, 5, 183, 124, 286, 75, 106, 74, 42, 91, 1, 168, 261, 54, 68, 217, 122, 162, 265, 71, 259, 210, 174, 290, 94, 17, 258, 9, 51, 53, 123, 280, 272, 240, 34, 99, 90, 115, 300, 218, 172, 119, 141, 215, 189, 188, 10, 182, 229, 105, 293, 242, 225, 305, 169, 57, 282, 88, 129, 55, 93, 11, 49, 233, 84, 48, 0, 22, 27, 216, 69, 36, 178, 52, 288, 58, 245, 65, 20, 281, 236, 262, 306, 244, 235, 238, 15, 186, 116, 152, 46, 311, 72, 206, 273, 62, 82, 243, 179, 107, 205, 274, 138, 297, 128, 254, 145, 267, 139, 14, 151, 185, 103, 228, 232, 194, 231, 153, 204, 50, 296, 192, 253, 213, 220, 184, 266, 112, 275, 4, 33, 101, 212, 100, 250, 89, 159, 279, 35, 291, 85, 37, 256, 308, 67, 222, 73, 180, 136, 135, 134, 303, 202, 175, 161, 264, 302, 120, 8, 41, 39, 310, 79, 283, 7, 25, 44, 97, 268, 121, 59, 227, 61, 234, 108, 224, 221, 156, 171, 181, 131, 211, 289, 76, 96, 148, 163, 63, 132, 23, 109, 66, 223, 140, 269, 277, 270, 80, 86, 12, 208, 285, 40, 56, 284, 43, 207, 301, 2, 87, 209, 173, 92, 230, 251, 30, 118, 113, 19, 114, 203, 176, 196, 170, 295, 133, 147, 195, 167, 255, 70, 190, 252, 16, 146, 125, 137, 309, 246, 278, 160, 249, 287, 165, 77, 98, 13, 257, 95, 32, 155, 198, 150, 214, 143, 193, 191, 177, 102, 158, 6, 127, 26, 144, 248, 45, 3, 47, 201, 197, 130, 83, 142, 29, 18, 260, 126, 200, 263, 298, 38, 239, 24, 78, 31, 247]
nv: 10 || Train: 50.027 || Val: 16.0
nv: 15 || Train: 61.623 || Val: 23.714
nv: 20 || Train: 77.656 || Val: 32.5
nv: 25 || Train: 81.916 || Val: 33.0
nv: 30 || Train: 85.522 || Val: 36.214
nv: 35 || Train: 87.661 || Val: 38.143
nv: 40 || Train: 88.439 || Val: 38.929
nv: 45 || Train: 89.765 || Val: 40.714
nv: 50 || Train: 91.303 || Val: 41.929
nv: 55 || Train: 92.346 || Val: 44.643
nv: 60 || Train: 92.699 || Val: 42.929
nv: 65 || Train: 92.982 || Val: 43.786
nv: 70 || Train: 93.212 || Val: 45.786
nv: 75 || Train: 93.601 || Val: 46.429
nv: 80 || Train: 93.954 || Val: 46.714
nv: 85 || Train: 94.255 || Val: 47.714
nv: 90 || Train: 94.255 || Val: 48.286
nv: 95 || Train: 94.485 || Val: 47.786
nv: 100 || Train: 94.502 || Val: 48.071
nv: 105 || Train: 94.856 || Val: 48.929
nv: 110 || Train: 95.209 || Val: 50.714
nv: 115 || Train: 95.263 || Val: 50.643
nv: 120 || Train: 95.475 || Val: 50.5
nv: 125 || Train: 95.492 || Val: 50.429
nv: 130 || Train: 95.439 || Val: 49.214
nv: 135 || Train: 95.581 || Val: 48.786
nv: 140 || Train: 95.386 || Val: 48.5
nv: 145 || Train: 95.545 || Val: 48.5
nv: 150 || Train: 95.298 || Val: 48.714
nv: 155 || Train: 95.598 || Val: 48.5
nv: 160 || Train: 95.881 || Val: 49.429
nv: 165 || Train: 96.058 || Val: 49.214
nv: 170 || Train: 95.793 || Val: 49.143
nv: 175 || Train: 95.811 || Val: 49.286
nv: 180 || Train: 95.793 || Val: 49.286
nv: 185 || Train: 95.952 || Val: 49.643
nv: 190 || Train: 96.04 || Val: 49.714
nv: 195 || Train: 96.111 || Val: 50.286
nv: 200 || Train: 96.04 || Val: 50.714
nv: 205 || Train: 95.952 || Val: 50.429
nv: 210 || Train: 96.023 || Val: 50.429
nv: 215 || Train: 96.005 || Val: 51.643
nv: 220 || Train: 96.076 || Val: 50.571
nv: 225 || Train: 96.358 || Val: 50.714
nv: 230 || Train: 96.5 || Val: 50.857
nv: 235 || Train: 96.535 || Val: 51.286
nv: 240 || Train: 96.323 || Val: 50.857
nv: 245 || Train: 96.482 || Val: 50.5
nv: 250 || Train: 96.553 || Val: 51.571
nv: 255 || Train: 96.677 || Val: 51.929
nv: 260 || Train: 96.694 || Val: 51.857
nv: 265 || Train: 96.588 || Val: 51.786
nv: 270 || Train: 96.571 || Val: 53.143
nv: 275 || Train: 96.588 || Val: 52.571
nv: 280 || Train: 96.677 || Val: 52.429
nv: 285 || Train: 96.694 || Val: 52.143
nv: 290 || Train: 96.783 || Val: 51.571
nv: 295 || Train: 96.942 || Val: 52.071
nv: 300 || Train: 96.836 || Val: 51.786
nv: 305 || Train: 96.853 || Val: 51.929
nv: 310 || Train: 96.853 || Val: 51.286
nv: 312 || Train: 96.836 || Val: 51.214
Fold 2...
Ranking: [296, 22, 133, 52, 130, 118, 89, 31, 242, 40, 106, 51, 117, 48, 269, 13, 286, 6, 293, 311, 87, 122, 171, 273, 263, 225, 60, 194, 14, 288, 36, 73, 8, 148, 70, 192, 138, 116, 186, 147, 145, 287, 140, 212, 254, 144, 274, 195, 276, 310, 292, 127, 236, 25, 217, 256, 104, 38, 92, 306, 252, 183, 285, 253, 248, 182, 255, 233, 246, 211, 282, 264, 260, 111, 203, 232, 241, 126, 54, 198, 168, 307, 153, 166, 302, 262, 29, 62, 234, 139, 137, 49, 75, 16, 91, 2, 41, 17, 90, 228, 170, 107, 290, 271, 113, 243, 44, 42, 67, 55, 97, 11, 251, 303, 199, 281, 277, 272, 220, 205, 215, 80, 160, 4, 238, 131, 50, 154, 58, 98, 109, 265, 93, 110, 19, 291, 175, 33, 226, 305, 181, 193, 208, 39, 151, 179, 298, 162, 270, 18, 222, 188, 206, 129, 128, 304, 275, 202, 201, 120, 68, 79, 45, 0, 82, 88, 132, 257, 197, 57, 164, 119, 230, 309, 56, 37, 24, 240, 227, 78, 108, 15, 294, 3, 204, 268, 136, 177, 191, 96, 9, 163, 209, 61, 125, 189, 214, 173, 210, 245, 150, 30, 101, 103, 161, 72, 280, 59, 224, 178, 53, 21, 295, 247, 297, 157, 83, 112, 105, 35, 149, 283, 239, 267, 66, 165, 167, 27, 47, 34, 23, 221, 135, 187, 142, 95, 284, 65, 308, 32, 5, 123, 258, 99, 158, 213, 300, 231, 169, 259, 184, 28, 235, 218, 174, 216, 63, 141, 26, 190, 10, 146, 1, 124, 250, 180, 102, 237, 43, 185, 81, 249, 289, 85, 219, 64, 76, 200, 77, 46, 94, 115, 134, 114, 86, 12, 279, 143, 176, 196, 244, 159, 20, 223, 266, 156, 84, 152, 121, 100, 69, 155, 7, 229, 301, 172, 207, 74, 299, 278, 71, 261]
nv: 10 || Train: 57.386 || Val: 20.614
nv: 15 || Train: 67.74 || Val: 24.505
nv: 20 || Train: 77.486 || Val: 29.078
nv: 25 || Train: 80.544 || Val: 30.239
nv: 30 || Train: 83.226 || Val: 31.058
nv: 35 || Train: 86.624 || Val: 31.331
nv: 40 || Train: 87.679 || Val: 32.901
nv: 45 || Train: 89.861 || Val: 36.246
nv: 50 || Train: 90.451 || Val: 36.109
nv: 55 || Train: 91.094 || Val: 38.84
nv: 60 || Train: 91.148 || Val: 37.679
nv: 65 || Train: 92.865 || Val: 38.84
nv: 70 || Train: 92.811 || Val: 39.932
nv: 75 || Train: 93.24 || Val: 39.044
nv: 80 || Train: 93.509 || Val: 38.908
nv: 85 || Train: 94.188 || Val: 40.0
nv: 90 || Train: 94.85 || Val: 41.911
nv: 95 || Train: 95.368 || Val: 42.73
nv: 100 || Train: 95.476 || Val: 42.594
nv: 105 || Train: 95.672 || Val: 43.891
nv: 110 || Train: 95.708 || Val: 43.686
nv: 115 || Train: 95.798 || Val: 44.71
nv: 120 || Train: 95.994 || Val: 42.73
nv: 125 || Train: 96.173 || Val: 43.413
nv: 130 || Train: 96.102 || Val: 43.276
nv: 135 || Train: 96.227 || Val: 44.71
nv: 140 || Train: 96.28 || Val: 44.71
nv: 145 || Train: 96.459 || Val: 44.846
nv: 150 || Train: 96.549 || Val: 45.666
nv: 155 || Train: 96.495 || Val: 45.666
nv: 160 || Train: 96.71 || Val: 45.529
nv: 165 || Train: 96.692 || Val: 46.143
nv: 170 || Train: 96.853 || Val: 45.802
nv: 175 || Train: 96.871 || Val: 44.437
nv: 180 || Train: 97.031 || Val: 45.188
nv: 185 || Train: 96.978 || Val: 45.119
nv: 190 || Train: 97.014 || Val: 45.324
nv: 195 || Train: 97.085 || Val: 44.915
nv: 200 || Train: 97.049 || Val: 44.437
nv: 205 || Train: 96.978 || Val: 44.505
nv: 210 || Train: 96.906 || Val: 44.846
nv: 215 || Train: 97.014 || Val: 44.369
nv: 220 || Train: 97.031 || Val: 45.597
nv: 225 || Train: 96.942 || Val: 45.461
nv: 230 || Train: 96.924 || Val: 45.666
nv: 235 || Train: 97.049 || Val: 45.666
nv: 240 || Train: 97.085 || Val: 45.324
nv: 245 || Train: 97.157 || Val: 46.007
nv: 250 || Train: 97.228 || Val: 45.461
nv: 255 || Train: 97.175 || Val: 45.802
nv: 260 || Train: 97.121 || Val: 45.666
nv: 265 || Train: 97.121 || Val: 45.597
nv: 270 || Train: 97.103 || Val: 45.802
nv: 275 || Train: 97.228 || Val: 46.007
nv: 280 || Train: 97.228 || Val: 46.485
nv: 285 || Train: 97.192 || Val: 45.939
nv: 290 || Train: 97.246 || Val: 46.416
nv: 295 || Train: 97.246 || Val: 46.28
nv: 300 || Train: 97.246 || Val: 45.87
nv: 305 || Train: 97.264 || Val: 45.802
nv: 310 || Train: 97.282 || Val: 46.075
nv: 312 || Train: 97.246 || Val: 46.485
Fold 3...
Ranking: [258, 49, 262, 181, 53, 68, 143, 255, 51, 89, 102, 21, 204, 98, 54, 32, 124, 292, 236, 92, 45, 149, 144, 278, 2, 254, 74, 218, 152, 219, 270, 240, 280, 87, 105, 130, 291, 77, 160, 286, 91, 132, 264, 305, 58, 15, 209, 30, 138, 9, 94, 304, 107, 246, 56, 111, 166, 142, 154, 185, 73, 167, 237, 217, 44, 100, 41, 171, 180, 61, 85, 78, 231, 122, 125, 196, 183, 175, 190, 0, 97, 308, 256, 285, 104, 126, 221, 121, 5, 281, 69, 263, 290, 22, 273, 34, 133, 233, 80, 223, 176, 162, 232, 222, 112, 238, 19, 155, 8, 192, 120, 279, 173, 36, 147, 295, 157, 39, 42, 288, 3, 28, 10, 63, 29, 79, 57, 177, 18, 96, 242, 62, 251, 202, 37, 188, 272, 75, 48, 148, 274, 161, 129, 137, 200, 310, 227, 266, 243, 156, 172, 206, 106, 64, 117, 195, 145, 25, 71, 271, 76, 220, 139, 201, 31, 244, 169, 119, 40, 250, 65, 23, 248, 93, 205, 289, 116, 17, 59, 210, 261, 275, 302, 267, 165, 187, 43, 84, 35, 135, 224, 207, 114, 186, 82, 247, 86, 16, 213, 297, 55, 81, 47, 299, 113, 141, 1, 208, 6, 67, 306, 241, 38, 168, 301, 66, 158, 230, 194, 184, 259, 179, 284, 268, 27, 182, 198, 134, 46, 95, 189, 110, 234, 164, 260, 283, 83, 276, 4, 294, 103, 216, 174, 170, 257, 60, 13, 90, 265, 115, 7, 163, 229, 108, 311, 33, 70, 215, 178, 298, 12, 14, 307, 140, 24, 239, 287, 11, 99, 109, 212, 228, 269, 245, 303, 128, 153, 88, 72, 199, 52, 197, 159, 211, 282, 235, 50, 193, 151, 191, 136, 226, 214, 309, 203, 123, 296, 146, 26, 249, 293, 127, 20, 101, 150, 252, 300, 118, 131, 225, 277, 253]
nv: 10 || Train: 39.129 || Val: 16.955
nv: 15 || Train: 61.718 || Val: 26.984
nv: 20 || Train: 68.083 || Val: 25.83
nv: 25 || Train: 77.641 || Val: 29.437
nv: 30 || Train: 79.81 || Val: 31.674
nv: 35 || Train: 83.936 || Val: 35.642
nv: 40 || Train: 86.616 || Val: 37.518
nv: 45 || Train: 87.445 || Val: 39.033
nv: 50 || Train: 89.702 || Val: 41.847
nv: 55 || Train: 90.584 || Val: 43.362
nv: 60 || Train: 90.989 || Val: 44.517
nv: 65 || Train: 91.747 || Val: 45.094
nv: 70 || Train: 92.47 || Val: 47.691
nv: 75 || Train: 92.806 || Val: 47.691
nv: 80 || Train: 92.982 || Val: 47.98
nv: 85 || Train: 93.282 || Val: 49.711
nv: 90 || Train: 93.405 || Val: 50.144
nv: 95 || Train: 93.934 || Val: 49.206
nv: 100 || Train: 93.881 || Val: 48.557
nv: 105 || Train: 93.987 || Val: 49.278
nv: 110 || Train: 94.287 || Val: 49.784
nv: 115 || Train: 94.269 || Val: 49.856
nv: 120 || Train: 94.251 || Val: 49.567
nv: 125 || Train: 94.269 || Val: 48.773
nv: 130 || Train: 95.168 || Val: 49.567
nv: 135 || Train: 95.221 || Val: 49.134
nv: 140 || Train: 95.451 || Val: 50.0
nv: 145 || Train: 95.592 || Val: 50.361
nv: 150 || Train: 95.821 || Val: 50.072
nv: 155 || Train: 95.909 || Val: 50.649
nv: 160 || Train: 95.997 || Val: 50.289
nv: 165 || Train: 96.244 || Val: 51.154
nv: 170 || Train: 96.121 || Val: 50.938
nv: 175 || Train: 96.121 || Val: 51.659
nv: 180 || Train: 96.156 || Val: 52.237
nv: 185 || Train: 96.191 || Val: 53.608
nv: 190 || Train: 96.367 || Val: 54.618
nv: 195 || Train: 96.35 || Val: 53.463
nv: 200 || Train: 96.544 || Val: 54.329
nv: 205 || Train: 96.561 || Val: 54.329
nv: 210 || Train: 96.561 || Val: 54.906
nv: 215 || Train: 96.561 || Val: 55.123
nv: 220 || Train: 96.544 || Val: 55.339
nv: 225 || Train: 96.65 || Val: 55.556
nv: 230 || Train: 96.703 || Val: 56.566
nv: 235 || Train: 96.65 || Val: 56.349
nv: 240 || Train: 96.579 || Val: 56.566
nv: 245 || Train: 96.826 || Val: 56.71
nv: 250 || Train: 96.791 || Val: 56.71
nv: 255 || Train: 96.844 || Val: 56.926
nv: 260 || Train: 96.914 || Val: 57.864
nv: 265 || Train: 96.914 || Val: 57.576
nv: 270 || Train: 96.879 || Val: 57.937
nv: 275 || Train: 97.002 || Val: 58.009
nv: 280 || Train: 97.002 || Val: 58.081
nv: 285 || Train: 97.073 || Val: 58.369
nv: 290 || Train: 96.949 || Val: 58.009
nv: 295 || Train: 96.914 || Val: 58.369
nv: 300 || Train: 96.967 || Val: 57.72
nv: 305 || Train: 97.055 || Val: 57.864
nv: 310 || Train: 97.038 || Val: 57.792
nv: 312 || Train: 97.073 || Val: 57.864
Fold 4...
Ranking: [144, 298, 246, 63, 157, 57, 229, 100, 199, 287, 14, 84, 41, 54, 198, 213, 169, 6, 284, 193, 250, 252, 121, 181, 290, 51, 148, 89, 235, 215, 97, 200, 292, 32, 87, 240, 23, 180, 161, 78, 297, 274, 251, 155, 216, 16, 146, 257, 167, 231, 194, 30, 49, 123, 12, 165, 205, 47, 2, 31, 195, 52, 151, 241, 277, 310, 308, 40, 92, 268, 217, 153, 91, 222, 4, 294, 98, 227, 25, 127, 72, 96, 302, 263, 300, 175, 189, 267, 108, 173, 170, 85, 145, 70, 248, 187, 166, 288, 42, 112, 286, 211, 249, 17, 13, 158, 38, 309, 265, 76, 311, 188, 244, 141, 142, 129, 71, 66, 10, 279, 19, 259, 1, 234, 204, 269, 55, 59, 272, 147, 172, 163, 275, 106, 281, 182, 207, 296, 68, 243, 159, 9, 107, 255, 37, 245, 214, 293, 183, 118, 111, 126, 254, 58, 307, 18, 178, 185, 139, 61, 104, 197, 79, 138, 39, 33, 280, 256, 225, 45, 102, 202, 120, 95, 0, 238, 26, 103, 34, 237, 212, 133, 125, 191, 83, 62, 114, 301, 305, 179, 29, 44, 27, 233, 230, 203, 299, 192, 24, 124, 101, 128, 77, 221, 208, 86, 73, 271, 15, 36, 130, 162, 186, 171, 88, 219, 67, 306, 81, 94, 69, 168, 140, 303, 270, 152, 260, 201, 5, 48, 262, 154, 75, 90, 119, 117, 149, 22, 56, 236, 131, 3, 116, 74, 295, 176, 264, 239, 247, 110, 210, 273, 304, 99, 261, 113, 134, 43, 60, 122, 278, 50, 150, 28, 174, 20, 283, 291, 93, 8, 105, 35, 285, 209, 184, 115, 220, 135, 228, 196, 218, 46, 276, 64, 177, 80, 282, 206, 242, 143, 65, 224, 132, 82, 226, 21, 11, 53, 164, 232, 137, 289, 190, 258, 136, 109, 156, 223, 253, 160, 7, 266]
nv: 10 || Train: 46.841 || Val: 19.275
nv: 15 || Train: 70.111 || Val: 27.809
nv: 20 || Train: 77.438 || Val: 29.587
nv: 25 || Train: 82.906 || Val: 32.361
nv: 30 || Train: 86.162 || Val: 30.725
nv: 35 || Train: 88.02 || Val: 31.65
nv: 40 || Train: 89.524 || Val: 33.997
nv: 45 || Train: 90.957 || Val: 34.211
nv: 50 || Train: 92.196 || Val: 34.851
nv: 55 || Train: 92.497 || Val: 34.211
nv: 60 || Train: 92.638 || Val: 37.909
nv: 65 || Train: 93.435 || Val: 37.127
nv: 70 || Train: 93.364 || Val: 39.189
nv: 75 || Train: 93.859 || Val: 40.398
nv: 80 || Train: 94.426 || Val: 39.189
nv: 85 || Train: 94.656 || Val: 39.829
nv: 90 || Train: 94.939 || Val: 39.189
nv: 95 || Train: 95.169 || Val: 40.114
nv: 100 || Train: 95.611 || Val: 40.114
nv: 105 || Train: 95.488 || Val: 39.26
nv: 110 || Train: 95.364 || Val: 39.403
nv: 115 || Train: 96.125 || Val: 39.616
nv: 120 || Train: 96.443 || Val: 40.541
nv: 125 || Train: 96.372 || Val: 41.181
nv: 130 || Train: 96.496 || Val: 42.745
nv: 135 || Train: 96.62 || Val: 42.532
nv: 140 || Train: 96.709 || Val: 43.457
nv: 145 || Train: 96.691 || Val: 44.381
nv: 150 || Train: 96.638 || Val: 44.381
nv: 155 || Train: 96.744 || Val: 45.661
nv: 160 || Train: 96.744 || Val: 45.804
nv: 165 || Train: 96.726 || Val: 46.302
nv: 170 || Train: 96.85 || Val: 46.302
nv: 175 || Train: 97.116 || Val: 46.088
nv: 180 || Train: 97.116 || Val: 45.448
nv: 185 || Train: 97.204 || Val: 45.804
nv: 190 || Train: 97.275 || Val: 46.159
nv: 195 || Train: 97.363 || Val: 45.377
nv: 200 || Train: 97.381 || Val: 46.302
nv: 205 || Train: 97.399 || Val: 46.373
nv: 210 || Train: 97.523 || Val: 45.519
nv: 215 || Train: 97.558 || Val: 45.519
nv: 220 || Train: 97.7 || Val: 46.017
nv: 225 || Train: 97.558 || Val: 46.088
nv: 230 || Train: 97.593 || Val: 46.373
nv: 235 || Train: 97.611 || Val: 46.657
nv: 240 || Train: 97.646 || Val: 46.586
nv: 245 || Train: 97.77 || Val: 47.013
nv: 250 || Train: 97.77 || Val: 47.226
nv: 255 || Train: 97.806 || Val: 47.155
nv: 260 || Train: 97.77 || Val: 48.08
nv: 265 || Train: 97.806 || Val: 47.582
nv: 270 || Train: 97.841 || Val: 47.795
nv: 275 || Train: 97.735 || Val: 48.222
nv: 280 || Train: 97.593 || Val: 47.866
nv: 285 || Train: 97.611 || Val: 47.937
nv: 290 || Train: 97.717 || Val: 47.937
nv: 295 || Train: 97.788 || Val: 48.506
nv: 300 || Train: 97.859 || Val: 48.435
nv: 305 || Train: 97.806 || Val: 48.933
nv: 310 || Train: 97.753 || Val: 48.649
nv: 312 || Train: 97.77 || Val: 48.435
Fold 5...
Ranking: [109, 14, 172, 143, 286, 287, 114, 255, 94, 230, 158, 11, 35, 205, 252, 245, 257, 121, 294, 309, 36, 267, 119, 50, 15, 254, 193, 20, 147, 154, 38, 260, 53, 52, 76, 202, 88, 123, 5, 266, 149, 194, 222, 116, 16, 69, 263, 8, 235, 178, 189, 72, 26, 128, 125, 146, 241, 67, 85, 291, 233, 71, 48, 46, 283, 12, 299, 308, 87, 13, 108, 275, 66, 195, 30, 137, 32, 296, 148, 297, 224, 206, 115, 171, 227, 24, 215, 288, 228, 246, 176, 218, 307, 232, 120, 47, 284, 237, 159, 133, 256, 75, 29, 269, 64, 44, 98, 127, 200, 80, 100, 9, 264, 51, 142, 141, 177, 251, 3, 6, 214, 150, 223, 152, 102, 271, 89, 184, 55, 92, 161, 164, 209, 207, 21, 182, 45, 68, 168, 274, 132, 130, 134, 7, 58, 49, 57, 217, 253, 293, 179, 78, 139, 261, 10, 310, 65, 31, 101, 90, 216, 157, 107, 170, 22, 27, 191, 124, 186, 82, 212, 295, 221, 62, 117, 301, 104, 2, 18, 162, 292, 144, 247, 239, 242, 110, 304, 0, 118, 91, 225, 262, 306, 129, 96, 70, 166, 173, 279, 183, 105, 4, 34, 84, 138, 236, 86, 238, 126, 231, 249, 95, 281, 303, 163, 289, 250, 73, 278, 305, 198, 37, 276, 113, 229, 199, 167, 180, 219, 140, 272, 136, 298, 156, 112, 211, 175, 17, 259, 204, 169, 300, 151, 244, 99, 188, 79, 190, 270, 201, 74, 103, 265, 213, 155, 181, 165, 268, 28, 43, 282, 33, 153, 280, 25, 106, 39, 59, 41, 243, 60, 131, 42, 81, 258, 302, 160, 40, 83, 234, 311, 97, 56, 197, 1, 277, 61, 273, 290, 77, 208, 111, 174, 210, 54, 63, 122, 23, 220, 145, 135, 248, 203, 285, 19, 196, 240, 93, 185, 226, 192, 187]
nv: 10 || Train: 50.751 || Val: 23.786
nv: 15 || Train: 69.524 || Val: 32.429
nv: 20 || Train: 78.823 || Val: 36.929
nv: 25 || Train: 83.825 || Val: 37.857
nv: 30 || Train: 86.442 || Val: 38.286
nv: 35 || Train: 88.351 || Val: 38.071
nv: 40 || Train: 89.535 || Val: 39.429
nv: 45 || Train: 90.861 || Val: 38.714
nv: 50 || Train: 91.356 || Val: 40.357
nv: 55 || Train: 91.833 || Val: 39.929
nv: 60 || Train: 92.805 || Val: 40.143
nv: 65 || Train: 93.071 || Val: 39.857
nv: 70 || Train: 93.159 || Val: 40.643
nv: 75 || Train: 94.255 || Val: 43.5
nv: 80 || Train: 94.626 || Val: 44.429
nv: 85 || Train: 94.414 || Val: 44.571
nv: 90 || Train: 94.715 || Val: 44.5
nv: 95 || Train: 94.98 || Val: 45.357
nv: 100 || Train: 95.28 || Val: 45.643
nv: 105 || Train: 95.28 || Val: 45.643
nv: 110 || Train: 95.704 || Val: 45.357
nv: 115 || Train: 95.987 || Val: 46.5
nv: 120 || Train: 96.04 || Val: 47.0
nv: 125 || Train: 96.04 || Val: 46.786
nv: 130 || Train: 95.97 || Val: 46.143
nv: 135 || Train: 96.111 || Val: 46.357
nv: 140 || Train: 96.535 || Val: 46.214
nv: 145 || Train: 96.394 || Val: 46.357
nv: 150 || Train: 96.412 || Val: 46.357
nv: 155 || Train: 96.394 || Val: 46.143
nv: 160 || Train: 96.394 || Val: 47.143
nv: 165 || Train: 96.323 || Val: 46.214
nv: 170 || Train: 96.305 || Val: 46.357
nv: 175 || Train: 96.394 || Val: 46.071
nv: 180 || Train: 96.341 || Val: 46.357
nv: 185 || Train: 96.341 || Val: 46.929
nv: 190 || Train: 96.429 || Val: 46.5
nv: 195 || Train: 96.376 || Val: 46.929
nv: 200 || Train: 96.465 || Val: 47.643
nv: 205 || Train: 96.641 || Val: 47.786
nv: 210 || Train: 96.588 || Val: 47.929
nv: 215 || Train: 96.659 || Val: 48.643
nv: 220 || Train: 96.712 || Val: 48.357
nv: 225 || Train: 96.677 || Val: 47.857
nv: 230 || Train: 96.712 || Val: 47.786
nv: 235 || Train: 96.694 || Val: 47.571
nv: 240 || Train: 96.571 || Val: 47.357
nv: 245 || Train: 96.606 || Val: 47.786
nv: 250 || Train: 96.694 || Val: 47.357
nv: 255 || Train: 96.624 || Val: 47.857
nv: 260 || Train: 96.641 || Val: 47.571
nv: 265 || Train: 96.641 || Val: 47.5
nv: 270 || Train: 96.624 || Val: 47.286
nv: 275 || Train: 96.783 || Val: 47.357
nv: 280 || Train: 96.73 || Val: 47.214
nv: 285 || Train: 96.765 || Val: 47.214
nv: 290 || Train: 96.836 || Val: 47.786
nv: 295 || Train: 96.765 || Val: 47.5
nv: 300 || Train: 96.836 || Val: 47.857
nv: 305 || Train: 96.871 || Val: 49.0
nv: 310 || Train: 97.013 || Val: 48.357
nv: 312 || Train: 97.03 || Val: 48.357
5
4
3
2
1
3
2
1
0

      Counts Attributes  Train Acc  Test Seen Acc  Test Unseen Acc
0          5     (245,)     93.184         60.261           41.523
1          4      (65,)     86.552         47.902           33.771
2          3       (2,)      3.259          2.098            5.460
3          2       (0,)      0.000          0.000            0.000
4          1       (0,)      0.000          0.000            0.000
5        5-4     (310,)     93.368         61.054           41.793
6      5-4-3     (312,)     93.411         60.941           41.692
7    5-4-3-2     (312,)     93.411         60.941           41.692
8  5-4-3-2-1     (312,)     93.411         60.941           41.692

# SUN

In [4]:
#################
### Arguments ###
#################
class Arguments:
    def __init__(self, dataset,seed,mode):
        self.dataset = dataset
        self.seed = seed
        self.mode = mode
        
         
DECIMAL_NUMBERS        = 3
FOLDS                  = 5
scaler_str             = 'Standard'     # ['Standard','MinMax']
orig_attribute         = False # Attributos originales u otros
debug                  = True 
SHOW                   = True

step                     = 5  # Paso de atributos a seleccionar [a, a+step, a+2*step, ...]
hitk = 1    
args = Arguments('SUN',42,'rfe') # MODE = RFE


#################
##### SetUp #####
#################
random.seed(args.seed)
np.random.seed(args.seed)
print(f"You've selected {args.dataset} dataset")
print(f"You've selected {args.mode} mode")
random_mode = False if args.mode == 'rfe' else True 
rfe_mode    = False if args.mode == 'random' else True

# Set up the path to the data
# Set up the path to the data
path_dir                  = pathlib.Path('data/')
path_data                 = path_dir / args.dataset  
results_dir               = pathlib.Path(f'Results/HAIS_v2/{args.dataset}') 


path_results_rfe_train_val    = results_dir / f'Wrapper{args.dataset}-RFE-train-val.csv'
path_results_random_val       = results_dir / f'Wrapper{args.dataset}-Random-val.csv' 
path_results_rfe_val_val      = results_dir / f'Wrapper{args.dataset}-RFE-val-val.csv'
path_results_random_simple    = results_dir / f'Wrapper{args.dataset}-Random-simple.csv' 

path_masks_rfe_train_val    = results_dir / f'Masks_{args.dataset}-RFE-train-val.csv'
path_masks_random_val       = results_dir / f'Masks_{args.dataset}-Random-val.csv' 
path_masks_rfe_val_val      = results_dir / f'Masks_{args.dataset}-RFE-val-val.csv'
path_masks_random_simple    = results_dir / f'Masks_{args.dataset}-Random-simple.csv' 

path_oracle_rfe_train_val    = results_dir / f'Oracle_Wrapper_{args.dataset}-RFE-train-val.csv'
path_oracle_random_val       = results_dir / f'Oracle_Wrapper_{args.dataset}-Random-val.csv' 
path_oracle_rfe_val_val      = results_dir / f'Oracle_Wrapper_{args.dataset}-RFE-val-val.csv'
path_oracle_random_simple    = results_dir / f'Oracle_Wrapper_{args.dataset}-Random-simple.csv' 

path_conteo_rfe_train_val    = results_dir / f'Conteo_{args.dataset}-RFE-train-val.csv'
path_conteo_random_val       = results_dir / f'Conteo_{args.dataset}-Random-val.csv' 
path_conteo_rfe_val_val      = results_dir / f'Conteo_{args.dataset}-RFE-val-val.csv'
path_conteo_random_simple    = results_dir / f'Conteo_{args.dataset}-Random-simple.csv' 



# Load the data
matcontent, att_splits = load_data_from_path(path_data, show = False)

"""
Comentar que en los datos de este datasets viene una partición establecida para train y val. Sin embargo, la partición de 'val' no contempla clases Unseen. Por tanto no la vamos usar.
Crearemos una partición de validación para clases Seen y Unseen a partir de la partición de test. 
Como conjunto de entrenamiento usaremos el que viene dado por los índices de la variable 'trainval_loc' en att_splits. 
Los índices de las varaibles 'train_loc' y 'val_loc' no los vamos a usar.
"""
# Get the data from att_splits dictionary
allclasses_names            = att_splits['allclasses_names']
original_att                = att_splits['original_att'].T.astype('float')  # Attributos originales
attribute                   = att_splits['att'].T.astype('float')           # Atributos que no se de donde salen, pero son los que usan <=== IMPORTANTE
# Indixes of the instances in the train, test and validation sets
test_unseen_loc             = att_splits['test_unseen_loc'].squeeze() - 1
test_seen_loc               = att_splits['test_seen_loc'].squeeze() - 1
trainval_loc                = att_splits['trainval_loc'].squeeze() - 1      # En caso de no usar validación, aquí estara todo el entrenamiento
train_loc                   = att_splits['train_loc'].squeeze() - 1         # Esto es si usamos validacion, ver comentario arriba
val_loc                     = att_splits['val_loc'].squeeze() -1            # Esto es si usamos validacion, ver comentario arriba
# Get the dta from matcontent dictionary
feature =  matcontent['features'].T                       # Feature Matrix (Number of instances x Number of features)
labels  =  matcontent['labels'].astype(int).squeeze() - 1 # Ponemos que sea entero, eliminamos la dimension extra y con el '-1' movemos el rango de [1,200] a [0,199]

random.shuffle(trainval_loc)
# Es importante usar aquí la matrices feature y labels originales
trainval_feature = feature[trainval_loc]
trainval_labels  = labels[trainval_loc]
trainval_classes = np.unique(trainval_labels)
random.shuffle(trainval_classes)

classes_per_fold = int(trainval_classes.shape[0] / FOLDS)
acarreo          = trainval_classes.shape[0] % FOLDS


# Get attributes and preprocessing them
attribute = original_att if orig_attribute else attribute
attribute = scaler_data(get_scaler(scaler_str),attribute)




#################
##### FOLDS #####
#################
folds = []
for i in range(FOLDS):
    
    # Gather data for the fold
    start = i * classes_per_fold
    end   = (i + 1) * classes_per_fold if i != FOLDS - 1 else (i + 1) * classes_per_fold + acarreo
    
    fold_i_val_classes       = trainval_classes[start:end] # Unseen
    fold_i_training_classes  = [x for x in trainval_classes if x not in fold_i_val_classes] # Seen
    
    fold_i_val_loc           = np.where(np.isin(trainval_labels, fold_i_val_classes)) # index for val
    fold_i_training_loc      = np.where(np.isin(trainval_labels, fold_i_training_classes)) # Index for training
    # np.isin(element,test_element) Calculates element in test_elements, broadcasting over element only. 
    # #Returns a boolean array of the same shape as element that is True where an element of element is in 
    # #test_elements and False otherwise.
    # np.where(lists[bool]) returns the indexes of the True values in the lists
    
    assert np.intersect1d(fold_i_val_loc, fold_i_training_loc).shape[0] == 0, f"Error: Problems found in creating folds {i}. Val and training classes are not disjoint"
    assert np.intersect1d(fold_i_val_classes, fold_i_training_classes).shape[0] == 0, f"Error: Problems found in creating folds {i}. Val and training classes are not disjoint"
    assert all([i not in fold_i_training_classes for i in trainval_labels[fold_i_val_loc]]), f"Error: Problems found in creating folds {i}"
    assert all([i not in fold_i_val_classes for i in trainval_labels[fold_i_training_loc]]), f"Error: Problems found in creating folds {i}"

    fold_i_training_features = trainval_feature[fold_i_training_loc]
    fold_i_val_features      = trainval_feature[fold_i_val_loc]
    fold_i_training_labels   = trainval_labels[fold_i_training_loc]
    fold_i_val_labels        = trainval_labels[fold_i_val_loc]
    fold_i_ss_val            = gen_ss_from_data(fold_i_val_labels,attribute)
    fold_i_ss_training       = gen_ss_from_data(fold_i_training_labels,attribute)
    
    assert np.intersect1d(np.unique(fold_i_val_labels),np.unique(fold_i_training_labels)).shape[0] == 0, f"Los conjuntos del fold {i+1} de etiquetas no son disjuntos"
    
    # Preprocess the data
    fold_i_training_features, fold_i_val_features = scaler_data(get_scaler(scaler_str),
                                                                fold_i_training_features,
                                                                fold_i_val_features)
    
    # Creating Datasets 
    fold_training = Dataset(features = fold_i_training_features, 
                            labels   = fold_i_training_labels, 
                            att      = fold_i_ss_training, 
                            mode     = 'train')
    
    fold_val      = Dataset(features = fold_i_val_features,
                            labels   = fold_i_val_labels,
                            att      = fold_i_ss_val,
                            mode     = 'val')
    
    fold = StackedDataset({'train':fold_training, 'val':fold_val})
    
    folds.append(fold)
    
    if SHOW:
        print(f"Fold {i+1} || Val Classes {np.unique(fold_i_val_labels).shape} - {fold_i_val_labels.shape} instances || Training Classes {np.unique(fold_i_training_labels).shape} - {fold_i_training_labels.shape} instances")

You've selected SUN dataset
You've selected rfe mode
Fold 1 || Val Classes (129,) - (2064,) instances || Training Classes (516,) - (8256,) instances
Fold 2 || Val Classes (129,) - (2064,) instances || Training Classes (516,) - (8256,) instances
Fold 3 || Val Classes (129,) - (2064,) instances || Training Classes (516,) - (8256,) instances
Fold 4 || Val Classes (129,) - (2064,) instances || Training Classes (516,) - (8256,) instances
Fold 5 || Val Classes (129,) - (2064,) instances || Training Classes (516,) - (8256,) instances

## Train Val

In [5]:
args = Arguments('SUN',42,'rfe') # MODE = RFE
random.seed(args.seed)
np.random.seed(args.seed)
print(f"You've selected {args.dataset} dataset")
print(f"You've selected {args.mode} mode")
random_mode = False if args.mode == 'rfe' else True 
rfe_mode    = False if args.mode == 'random' else True

vattributes = np.arange(10, attribute.shape[1], step)
if attribute.shape[1] % step != 0:
    vattributes = np.append(vattributes, attribute.shape[1])

conteo          = np.zeros(attribute.shape[1])
best_folds_configuration = [] # Mejor configurración de atributos seleccionados en cada uno de los folds
for i, fold in enumerate(folds):

    print(f"Fold {i+1}...")

    training_data = fold.datasets['train']
    val_data      = fold.datasets['val']

    attributes_X_train = training_data.att.copy()

    rfe = RFE(estimator = None, estimator_name = 'SAE', n_features_to_select = 1, step = 1, verbose = True)
    rfe.fit(training_data.features, training_data.att,training_data.labels)
    ranking = rfe.get_ranking()
    
    fold_i_att_acc = {'Attributes': [],
                      'Train Acc': [],
                      'Val Acc': [],
                      'Mask':[]}
    
    for nv in vattributes:
        
        mask = ranking <= nv
        W = SAE(training_data.features.T, training_data.att[:,mask].T,500000) 
        # Training Acc
        gt_ss_training_adapted  = attribute[training_data.classes][:,mask]
        semantic_predicted = np.dot(training_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, training_data.classes,training_data.labels)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        # Val Acc
        gt_ss_val_adapted    = attribute[val_data.classes][:,mask]
        semantic_predicted = np.dot(val_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, val_data.classes,val_data.labels)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        # Save results
        fold_i_att_acc['Attributes'].append(nv)
        fold_i_att_acc['Train Acc'].append(zsl_accuracy_train)
        fold_i_att_acc['Val Acc'].append(zsl_accuracy1_unseen)
        fold_i_att_acc['Mask'].append(mask)
        
        if debug:
            print(f"nv: {nv} || Train: {zsl_accuracy_train} || Val: {zsl_accuracy1_unseen}")
    # Saving the best configuration of the fold
    fold_i_att_acc = pd.DataFrame(fold_i_att_acc).sort_values(by = 'Val Acc', ascending = False)
    best_folds_configuration.append(fold_i_att_acc.iloc[0])
    

for res in best_folds_configuration:
    conteo = conteo + np.asarray(res['Mask']).astype(int)
    
    
df = {}
for i in range(len(best_folds_configuration)):
    df[i] = best_folds_configuration[i].to_dict()
df = pd.DataFrame(df).T

if rfe_mode: 
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_rfe_train_val)
else:
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_random_val)
    
    
    
    
# Evaluamos en test 
test_results = {'Counts':[],'Attributes':[],'Train Acc':[],'Test Seen Acc':[],'Test Unseen Acc':[]}
j = 1
cadena = '5'
for i in range(FOLDS*2-1):
    if i < FOLDS:
        test_results['Counts'].append(str(FOLDS-i))
        test_results['Attributes'].append(np.where(conteo==FOLDS-i)[0].shape)
        mejores = np.where(conteo==FOLDS-i)[0]

    else:
        cadena = cadena+'-'+str(FOLDS-j)
        test_results['Counts'].append(cadena)
        test_results['Attributes'].append(np.where(conteo>=FOLDS-j)[0].shape)
        mejores = np.where(conteo>=FOLDS-j)[0]
        j+=1

    
    
    if mejores.shape[0] > 0:
        # Training
        training_feature = feature[trainval_loc]
        training_label   = labels[trainval_loc]
        ss_training      = gen_ss_from_data(training_label,attribute)
        # Get test
        test_unseen_feature = feature[test_unseen_loc]
        test_unseen_label   = labels[test_unseen_loc]
        ss_test_unseen      = gen_ss_from_data(test_unseen_label,attribute)
        test_seen_feature = feature[test_seen_loc]
        test_seen_label   = labels[test_seen_loc]
        ss_test_seen      = gen_ss_from_data(test_seen_label,attribute)
        # Preprocessing
        scaler = get_scaler(scaler_str)
        scaler.fit(training_feature)
        training_feature = scaler.transform(training_feature)
        test_unseen_feature = scaler.transform(test_unseen_feature)
        test_seen_feature = scaler.transform(test_seen_feature)
        # Fit the model
        W = SAE(training_feature.T, ss_training[:,mejores].T,500000) 
        gt_ss_training_adapted  = attribute[np.unique(training_label)][:,mejores]
        semantic_predicted = np.dot(training_feature, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, np.unique(training_label),training_label)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        test_results['Train Acc'].append(zsl_accuracy_train)
        # Evaluo en test seen
        gt_ss_val_adapted    = attribute[np.unique(test_seen_label)][:,mejores]
        semantic_predicted = np.dot(test_seen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_seen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_seen_label),test_seen_label)
        zsl_accuracy1_seen = round(zsl_accuracy1_seen,DECIMAL_NUMBERS)
        test_results['Test Seen Acc'].append(zsl_accuracy1_seen)
        # Evaluo en test unseen
        gt_ss_val_adapted    = attribute[np.unique(test_unseen_label)][:,mejores]
        semantic_predicted = np.dot(test_unseen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_unseen_label),test_unseen_label)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        test_results['Test Unseen Acc'].append(zsl_accuracy1_unseen)
    else:
        test_results['Train Acc'].append(0)
        test_results['Test Seen Acc'].append(0)
        test_results['Test Unseen Acc'].append(0)
    
if rfe_mode:
    pd.DataFrame(test_results).to_csv(path_oracle_rfe_train_val)
else:
    pd.DataFrame(test_results).to_csv(path_oracle_random_val)
    
pd.DataFrame(test_results)

You've selected SUN dataset
You've selected rfe mode
Fold 1...
Ranking: [51, 58, 24, 63, 5, 26, 7, 12, 2, 43, 101, 60, 71, 55, 44, 18, 19, 59, 48, 100, 87, 97, 47, 99, 10, 98, 22, 50, 11, 52, 9, 95, 33, 29, 42, 45, 34, 39, 27, 65, 70, 17, 31, 16, 23, 82, 20, 37, 1, 89, 69, 73, 32, 68, 21, 46, 6, 57, 28, 78, 83, 41, 79, 84, 15, 96, 35, 93, 64, 74, 77, 91, 62, 38, 53, 25, 3, 56, 4, 14, 40, 85, 86, 94, 90, 72, 54, 30, 67, 36, 61, 49, 88, 66, 13, 92, 8, 80, 81, 76, 0, 75]
nv: 10 || Train: 20.422 || Val: 13.421
nv: 15 || Train: 30.85 || Val: 15.116
nv: 20 || Train: 38.215 || Val: 17.733
nv: 25 || Train: 43.593 || Val: 21.415
nv: 30 || Train: 49.31 || Val: 25.436
nv: 35 || Train: 52.289 || Val: 25.824
nv: 40 || Train: 53.646 || Val: 27.229
nv: 45 || Train: 57.207 || Val: 29.457
nv: 50 || Train: 58.442 || Val: 31.541
nv: 55 || Train: 59.193 || Val: 32.558
nv: 60 || Train: 61.301 || Val: 34.012
nv: 65 || Train: 63.59 || Val: 34.545
nv: 70 || Train: 64.971 || Val: 35.465
nv: 75 || Train: 67.297 || Val: 35.756
nv: 80 || Train: 68.52 || Val: 36.725
nv: 85 || Train: 69.356 || Val: 37.161
nv: 90 || Train: 70.676 || Val: 38.324
nv: 95 || Train: 71.088 || Val: 38.614
nv: 100 || Train: 71.463 || Val: 39.438
nv: 102 || Train: 71.596 || Val: 39.535
Fold 2...
Ranking: [71, 26, 19, 18, 59, 87, 99, 60, 101, 11, 15, 65, 22, 7, 85, 23, 12, 16, 8, 68, 3, 44, 10, 80, 33, 95, 63, 49, 9, 6, 53, 100, 20, 56, 51, 89, 21, 58, 45, 24, 28, 42, 30, 40, 55, 0, 81, 84, 97, 54, 37, 77, 66, 13, 96, 32, 50, 67, 31, 94, 4, 2, 76, 92, 83, 39, 27, 93, 29, 1, 88, 72, 14, 34, 90, 46, 35, 52, 78, 86, 5, 74, 91, 41, 17, 43, 36, 70, 57, 73, 47, 98, 82, 69, 25, 61, 62, 48, 75, 38, 64, 79]
nv: 10 || Train: 15.334 || Val: 11.822
nv: 15 || Train: 24.588 || Val: 17.345
nv: 20 || Train: 34.242 || Val: 20.979
nv: 25 || Train: 40.068 || Val: 22.674
nv: 30 || Train: 43.132 || Val: 24.419
nv: 35 || Train: 47.953 || Val: 26.114
nv: 40 || Train: 51.284 || Val: 27.229
nv: 45 || Train: 54.591 || Val: 28.44
nv: 50 || Train: 59.436 || Val: 31.686
nv: 55 || Train: 60.938 || Val: 32.219
nv: 60 || Train: 63.094 || Val: 33.382
nv: 65 || Train: 66.388 || Val: 35.223
nv: 70 || Train: 67.672 || Val: 35.659
nv: 75 || Train: 68.387 || Val: 36.192
nv: 80 || Train: 69.44 || Val: 36.337
nv: 85 || Train: 70.591 || Val: 36.628
nv: 90 || Train: 71.281 || Val: 37.306
nv: 95 || Train: 72.626 || Val: 38.663
nv: 100 || Train: 72.481 || Val: 38.857
nv: 102 || Train: 72.384 || Val: 39.39
Fold 3...
Ranking: [11, 12, 101, 19, 55, 59, 26, 18, 10, 71, 28, 29, 51, 99, 58, 22, 87, 100, 44, 68, 34, 95, 45, 20, 21, 65, 52, 1, 15, 40, 30, 50, 98, 80, 83, 25, 3, 16, 35, 23, 84, 31, 7, 54, 76, 57, 96, 24, 62, 0, 63, 89, 33, 94, 8, 93, 39, 36, 97, 90, 82, 42, 37, 74, 77, 9, 61, 38, 53, 91, 47, 4, 81, 6, 78, 49, 17, 56, 75, 2, 48, 67, 70, 66, 32, 41, 43, 69, 73, 46, 5, 86, 79, 27, 92, 60, 72, 14, 85, 13, 64, 88]
nv: 10 || Train: 18.496 || Val: 13.324
nv: 15 || Train: 27.786 || Val: 18.217
nv: 20 || Train: 36.604 || Val: 22.82
nv: 25 || Train: 40.274 || Val: 26.26
nv: 30 || Train: 44.344 || Val: 27.326
nv: 35 || Train: 49.915 || Val: 30.814
nv: 40 || Train: 55.535 || Val: 32.607
nv: 45 || Train: 59.205 || Val: 35.223
nv: 50 || Train: 60.32 || Val: 34.254
nv: 55 || Train: 62.246 || Val: 35.659
nv: 60 || Train: 64.244 || Val: 37.791
nv: 65 || Train: 66.194 || Val: 38.324
nv: 70 || Train: 66.788 || Val: 38.469
nv: 75 || Train: 68.762 || Val: 39.68
nv: 80 || Train: 69.174 || Val: 40.552
nv: 85 || Train: 70.058 || Val: 41.037
nv: 90 || Train: 71.039 || Val: 41.521
nv: 95 || Train: 72.129 || Val: 41.182
nv: 100 || Train: 72.372 || Val: 41.328
nv: 102 || Train: 72.432 || Val: 41.521
Fold 4...
Ranking: [83, 12, 16, 11, 60, 51, 52, 55, 32, 31, 18, 68, 85, 26, 71, 19, 59, 97, 84, 80, 10, 63, 20, 101, 9, 15, 65, 29, 33, 24, 87, 58, 22, 2, 95, 66, 44, 75, 78, 53, 34, 8, 48, 0, 64, 54, 3, 70, 37, 76, 4, 62, 81, 23, 99, 38, 28, 36, 67, 45, 30, 77, 49, 21, 7, 56, 27, 6, 35, 88, 73, 74, 43, 72, 86, 93, 94, 39, 69, 91, 61, 100, 47, 40, 50, 25, 17, 14, 98, 89, 13, 82, 96, 90, 79, 57, 46, 41, 92, 42, 1, 5]
nv: 10 || Train: 18.823 || Val: 12.548
nv: 15 || Train: 28.609 || Val: 17.926
nv: 20 || Train: 34.726 || Val: 20.736
nv: 25 || Train: 44.247 || Val: 23.547
nv: 30 || Train: 49.576 || Val: 25.533
nv: 35 || Train: 52.495 || Val: 26.599
nv: 40 || Train: 56.577 || Val: 27.713
nv: 45 || Train: 60.804 || Val: 28.585
nv: 50 || Train: 63.493 || Val: 29.021
nv: 55 || Train: 64.377 || Val: 29.99
nv: 60 || Train: 65.601 || Val: 31.589
nv: 65 || Train: 66.8 || Val: 32.558
nv: 70 || Train: 67.793 || Val: 33.333
nv: 75 || Train: 68.75 || Val: 34.593
nv: 80 || Train: 69.683 || Val: 35.707
nv: 85 || Train: 70.458 || Val: 36.386
nv: 90 || Train: 70.47 || Val: 36.24
nv: 95 || Train: 71.245 || Val: 37.016
nv: 100 || Train: 71.524 || Val: 37.597
nv: 102 || Train: 71.451 || Val: 37.645
Fold 5...
Ranking: [84, 12, 101, 59, 54, 33, 52, 11, 15, 99, 24, 71, 19, 26, 85, 87, 55, 78, 80, 63, 30, 36, 82, 45, 58, 68, 10, 23, 60, 7, 97, 22, 67, 28, 66, 31, 100, 49, 53, 2, 98, 32, 44, 39, 96, 51, 75, 3, 0, 35, 37, 48, 77, 18, 47, 61, 4, 25, 56, 83, 95, 42, 21, 86, 5, 72, 46, 90, 9, 8, 34, 69, 64, 17, 29, 57, 6, 14, 94, 81, 74, 92, 1, 89, 40, 43, 27, 93, 41, 20, 70, 88, 73, 62, 38, 50, 79, 16, 65, 13, 76, 91]
nv: 10 || Train: 16.037 || Val: 11.967
nv: 15 || Train: 29.118 || Val: 17.006
nv: 20 || Train: 37.318 || Val: 20.785
nv: 25 || Train: 43.35 || Val: 22.674
nv: 30 || Train: 46.378 || Val: 24.128
nv: 35 || Train: 50.545 || Val: 26.793
nv: 40 || Train: 54.821 || Val: 27.616
nv: 45 || Train: 56.662 || Val: 29.264
nv: 50 || Train: 60.405 || Val: 30.184
nv: 55 || Train: 62.415 || Val: 31.298
nv: 60 || Train: 63.796 || Val: 32.074
nv: 65 || Train: 65.71 || Val: 33.866
nv: 70 || Train: 67.236 || Val: 35.174
nv: 75 || Train: 68.06 || Val: 35.417
nv: 80 || Train: 69.671 || Val: 36.579
nv: 85 || Train: 71.015 || Val: 37.5
nv: 90 || Train: 71.378 || Val: 38.13
nv: 95 || Train: 71.693 || Val: 38.372
nv: 100 || Train: 72.032 || Val: 38.614
nv: 102 || Train: 72.178 || Val: 38.663

      Counts Attributes  Train Acc  Test Seen Acc  Test Unseen Acc
0          5     (102,)     61.531         29.419           47.153
1          4       (0,)      0.000          0.000            0.000
2          3       (0,)      0.000          0.000            0.000
3          2       (0,)      0.000          0.000            0.000
4          1       (0,)      0.000          0.000            0.000
5        5-4     (102,)     61.531         29.419           47.153
6      5-4-3     (102,)     61.531         29.419           47.153
7    5-4-3-2     (102,)     61.531         29.419           47.153
8  5-4-3-2-1     (102,)     61.531         29.419           47.153

## Val Val

In [6]:
args = Arguments('SUN',42,'rfe') # MODE = RFE


random.seed(args.seed)
np.random.seed(args.seed)
print(f"You've selected {args.dataset} dataset")
print(f"You've selected {args.mode} mode")
random_mode = False if args.mode == 'rfe' else True 
rfe_mode    = False if args.mode == 'random' else True




vattributes = np.arange(10, attribute.shape[1], step)
if attribute.shape[1] % step != 0:
    vattributes = np.append(vattributes, attribute.shape[1])

conteo          = np.zeros(attribute.shape[1])
best_folds_configuration = [] # Mejor configurración de atributos seleccionados en cada uno de los folds
for i, fold in enumerate(folds):

    print(f"Fold {i+1}...")

    training_data = fold.datasets['train']
    val_data      = fold.datasets['val']



    rfe = RFE(estimator = None, estimator_name = 'SAE', n_features_to_select = 1, step = 1, verbose = True)
    rfe.fit(val_data.features, val_data.att,val_data.labels)
    ranking = rfe.get_ranking()
    
    fold_i_att_acc = {'Attributes': [],
                      'Train Acc': [],
                      'Val Acc': [],
                      'Mask':[]}
    
    for nv in vattributes:
        
        mask = ranking <= nv
        W = SAE(training_data.features.T, training_data.att[:,mask].T,500000) 
        # Training Acc
        gt_ss_training_adapted  = attribute[training_data.classes][:,mask]
        semantic_predicted = np.dot(training_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, training_data.classes,training_data.labels)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        # Val Acc
        gt_ss_val_adapted    = attribute[val_data.classes][:,mask]
        semantic_predicted = np.dot(val_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, val_data.classes,val_data.labels)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        # Save results
        fold_i_att_acc['Attributes'].append(nv)
        fold_i_att_acc['Train Acc'].append(zsl_accuracy_train)
        fold_i_att_acc['Val Acc'].append(zsl_accuracy1_unseen)
        fold_i_att_acc['Mask'].append(mask)
        
        if debug:
            print(f"nv: {nv} || Train: {zsl_accuracy_train} || Val: {zsl_accuracy1_unseen}")
    # Saving the best configuration of the fold
    fold_i_att_acc = pd.DataFrame(fold_i_att_acc).sort_values(by = 'Val Acc', ascending = False)
    best_folds_configuration.append(fold_i_att_acc.iloc[0])
    

for res in best_folds_configuration:
    conteo = conteo + np.asarray(res['Mask']).astype(int)
   
   
   
   
df = {}
for i in range(len(best_folds_configuration)):
    df[i] = best_folds_configuration[i].to_dict()
df = pd.DataFrame(df).T

if rfe_mode: # Los mejores resultados de cada fold y el conteo
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_rfe_val_val)
else:
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_random_val)
    
    
    
    
    
    
    
    
# Evaluamos en test 
test_results = {'Counts':[],'Attributes':[],'Train Acc':[],'Test Seen Acc':[],'Test Unseen Acc':[]}
j = 1
cadena = '5'
for i in range(FOLDS*2-1):
    if i < FOLDS:
        test_results['Counts'].append(str(FOLDS-i))
        test_results['Attributes'].append(np.where(conteo==FOLDS-i)[0].shape)
        mejores = np.where(conteo==FOLDS-i)[0]
        print(FOLDS-i)
    else:
        cadena = cadena+'-'+str(FOLDS-j)
        test_results['Counts'].append(cadena)
        test_results['Attributes'].append(np.where(conteo>=FOLDS-j)[0].shape)
        mejores = np.where(conteo>=FOLDS-j)[0]
        j+=1
        print(FOLDS-j)
    
    
    if mejores.shape[0] > 0:
        # Training
        training_feature = feature[trainval_loc].copy()
        training_label   = labels[trainval_loc].copy()
        ss_training      = gen_ss_from_data(training_label,attribute)
        # Get test
        test_unseen_feature = feature[test_unseen_loc].copy()
        test_unseen_label   = labels[test_unseen_loc].copy()
        ss_test_unseen      = gen_ss_from_data(test_unseen_label,attribute)
        test_seen_feature = feature[test_seen_loc].copy()
        test_seen_label   = labels[test_seen_loc].copy()
        ss_test_seen      = gen_ss_from_data(test_seen_label,attribute)
        # Preprocessing
        scaler = get_scaler(scaler_str)
        scaler.fit(training_feature)
        training_feature = scaler.transform(training_feature)
        test_unseen_feature = scaler.transform(test_unseen_feature)
        test_seen_feature = scaler.transform(test_seen_feature)
        # Fit the model
        W = SAE(training_feature.T, ss_training[:,mejores].T,500000) 
        gt_ss_training_adapted  = attribute[np.unique(training_label)][:,mejores]
        semantic_predicted = np.dot(training_feature, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, np.unique(training_label),training_label)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        test_results['Train Acc'].append(zsl_accuracy_train)
        # Evaluo en test seen
        gt_ss_val_adapted    = attribute[np.unique(test_seen_label)][:,mejores]
        semantic_predicted = np.dot(test_seen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_seen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_seen_label),test_seen_label)
        zsl_accuracy1_seen = round(zsl_accuracy1_seen,DECIMAL_NUMBERS)
        test_results['Test Seen Acc'].append(zsl_accuracy1_seen)
        # Evaluo en test unseen
        gt_ss_val_adapted    = attribute[np.unique(test_unseen_label)][:,mejores]
        semantic_predicted = np.dot(test_unseen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_unseen_label),test_unseen_label)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        test_results['Test Unseen Acc'].append(zsl_accuracy1_unseen)
    else:
        test_results['Train Acc'].append(0)
        test_results['Test Seen Acc'].append(0)
        test_results['Test Unseen Acc'].append(0)
    
if rfe_mode:
    pd.DataFrame(test_results).to_csv(path_oracle_rfe_val_val)
else:
    pd.DataFrame(test_results).to_csv(path_oracle_random_val)
    
pd.DataFrame(test_results)

You've selected SUN dataset
You've selected rfe mode
Fold 1...
Ranking: [58, 29, 64, 84, 98, 5, 53, 55, 90, 62, 52, 32, 37, 7, 59, 31, 19, 46, 47, 44, 92, 45, 82, 50, 28, 39, 23, 16, 65, 36, 21, 41, 35, 11, 26, 10, 22, 70, 77, 51, 34, 60, 85, 95, 88, 1, 54, 73, 20, 61, 78, 27, 8, 93, 80, 97, 101, 18, 74, 66, 40, 13, 15, 76, 33, 83, 72, 43, 4, 71, 48, 3, 75, 68, 24, 100, 0, 99, 56, 2, 42, 30, 87, 17, 89, 38, 94, 63, 12, 91, 9, 57, 69, 25, 67, 81, 14, 49, 96, 6, 86, 79]
nv: 10 || Train: 20.797 || Val: 13.517
nv: 15 || Train: 32.485 || Val: 18.362
nv: 20 || Train: 40.879 || Val: 21.56
nv: 25 || Train: 44.985 || Val: 24.322
nv: 30 || Train: 51.017 || Val: 27.519
nv: 35 || Train: 55.584 || Val: 30.281
nv: 40 || Train: 58.854 || Val: 31.783
nv: 45 || Train: 61.337 || Val: 32.558
nv: 50 || Train: 62.379 || Val: 33.672
nv: 55 || Train: 64.62 || Val: 34.302
nv: 60 || Train: 64.668 || Val: 34.109
nv: 65 || Train: 65.346 || Val: 34.593
nv: 70 || Train: 66.255 || Val: 35.32
nv: 75 || Train: 67.151 || Val: 35.901
nv: 80 || Train: 68.532 || Val: 37.403
nv: 85 || Train: 68.823 || Val: 37.548
nv: 90 || Train: 69.913 || Val: 37.161
nv: 95 || Train: 70.228 || Val: 37.694
nv: 100 || Train: 71.088 || Val: 38.711
nv: 102 || Train: 71.596 || Val: 39.535
Fold 2...
Ranking: [90, 100, 11, 79, 96, 28, 3, 97, 12, 89, 46, 45, 10, 25, 65, 7, 99, 53, 2, 32, 85, 24, 30, 19, 54, 61, 35, 71, 82, 94, 68, 57, 64, 87, 84, 95, 80, 21, 69, 26, 31, 78, 67, 34, 75, 6, 43, 38, 63, 52, 98, 22, 16, 23, 66, 29, 76, 51, 60, 86, 50, 5, 36, 9, 14, 15, 55, 73, 77, 18, 27, 47, 83, 74, 44, 13, 37, 41, 39, 59, 62, 20, 101, 49, 1, 88, 40, 92, 56, 42, 93, 72, 4, 33, 17, 70, 0, 81, 58, 91, 48, 8]
nv: 10 || Train: 21.851 || Val: 13.663
nv: 15 || Train: 31.977 || Val: 19.331
nv: 20 || Train: 38.881 || Val: 22.045
nv: 25 || Train: 45.228 || Val: 24.952
nv: 30 || Train: 49.964 || Val: 26.841
nv: 35 || Train: 52.156 || Val: 28.731
nv: 40 || Train: 55.317 || Val: 29.312
nv: 45 || Train: 57.074 || Val: 29.409
nv: 50 || Train: 58.794 || Val: 31.395
nv: 55 || Train: 61.24 || Val: 32.703
nv: 60 || Train: 64.184 || Val: 34.157
nv: 65 || Train: 65.577 || Val: 33.721
nv: 70 || Train: 67.066 || Val: 34.399
nv: 75 || Train: 66.533 || Val: 34.641
nv: 80 || Train: 68.144 || Val: 36.24
nv: 85 || Train: 69.913 || Val: 36.822
nv: 90 || Train: 70.954 || Val: 37.258
nv: 95 || Train: 71.487 || Val: 38.227
nv: 100 || Train: 72.238 || Val: 38.857
nv: 102 || Train: 72.384 || Val: 39.39
Fold 3...
Ranking: [84, 83, 37, 22, 40, 5, 12, 78, 23, 47, 26, 65, 82, 77, 90, 48, 4, 66, 67, 92, 20, 46, 79, 9, 21, 69, 15, 53, 1, 39, 36, 72, 31, 30, 63, 64, 2, 96, 28, 56, 7, 11, 45, 34, 38, 94, 10, 61, 99, 74, 43, 54, 98, 81, 0, 33, 95, 16, 75, 42, 89, 29, 50, 57, 76, 25, 68, 97, 27, 41, 14, 100, 49, 59, 70, 60, 58, 91, 88, 51, 71, 6, 35, 18, 55, 93, 80, 3, 44, 52, 85, 8, 32, 17, 24, 86, 73, 19, 13, 87, 101, 62]
nv: 10 || Train: 17.393 || Val: 14.68
nv: 15 || Train: 26.732 || Val: 19.477
nv: 20 || Train: 37.464 || Val: 24.952
nv: 25 || Train: 41.655 || Val: 26.647
nv: 30 || Train: 45.579 || Val: 28.924
nv: 35 || Train: 50.182 || Val: 30.233
nv: 40 || Train: 52.471 || Val: 30.862
nv: 45 || Train: 55.887 || Val: 32.171
nv: 50 || Train: 57.716 || Val: 33.43
nv: 55 || Train: 60.126 || Val: 34.738
nv: 60 || Train: 60.768 || Val: 34.835
nv: 65 || Train: 63.796 || Val: 35.95
nv: 70 || Train: 64.365 || Val: 36.87
nv: 75 || Train: 66.715 || Val: 37.694
nv: 80 || Train: 67.963 || Val: 38.469
nv: 85 || Train: 68.992 || Val: 39.486
nv: 90 || Train: 70.119 || Val: 40.359
nv: 95 || Train: 71.269 || Val: 40.891
nv: 100 || Train: 72.299 || Val: 41.667
nv: 102 || Train: 72.432 || Val: 41.521
Fold 4...
Ranking: [90, 82, 20, 27, 29, 46, 48, 34, 98, 28, 40, 18, 76, 10, 37, 45, 8, 74, 68, 35, 2, 100, 73, 43, 1, 77, 39, 56, 7, 95, 101, 63, 51, 13, 58, 49, 92, 47, 44, 78, 32, 30, 11, 33, 61, 83, 62, 91, 79, 88, 3, 5, 71, 38, 12, 4, 80, 50, 9, 64, 84, 53, 15, 85, 99, 86, 41, 97, 42, 36, 87, 89, 55, 21, 75, 96, 17, 65, 57, 72, 54, 67, 16, 14, 93, 26, 59, 94, 22, 0, 81, 23, 19, 52, 25, 24, 60, 31, 69, 70, 66, 6]
nv: 10 || Train: 18.072 || Val: 11.143
nv: 15 || Train: 29.033 || Val: 15.94
nv: 20 || Train: 39.087 || Val: 19.428
nv: 25 || Train: 44.392 || Val: 23.304
nv: 30 || Train: 50.533 || Val: 25.824
nv: 35 || Train: 55.087 || Val: 27.229
nv: 40 || Train: 56.783 || Val: 27.713
nv: 45 || Train: 58.721 || Val: 29.264
nv: 50 || Train: 60.768 || Val: 31.783
nv: 55 || Train: 62.197 || Val: 32.316
nv: 60 || Train: 65.686 || Val: 33.188
nv: 65 || Train: 66.485 || Val: 34.738
nv: 70 || Train: 67.963 || Val: 35.029
nv: 75 || Train: 68.653 || Val: 35.465
nv: 80 || Train: 69.537 || Val: 36.24
nv: 85 || Train: 70.203 || Val: 36.531
nv: 90 || Train: 70.882 || Val: 36.434
nv: 95 || Train: 70.894 || Val: 36.725
nv: 100 || Train: 71.306 || Val: 37.597
nv: 102 || Train: 71.451 || Val: 37.645
Fold 5...
Ranking: [63, 37, 50, 61, 59, 67, 49, 60, 100, 65, 4, 83, 16, 71, 78, 64, 77, 5, 72, 85, 8, 20, 0, 66, 31, 70, 3, 79, 51, 87, 7, 38, 62, 96, 40, 53, 101, 33, 35, 93, 57, 41, 73, 22, 6, 82, 23, 25, 68, 75, 92, 56, 36, 32, 55, 95, 42, 88, 80, 11, 46, 15, 39, 48, 10, 89, 47, 13, 29, 44, 28, 14, 18, 26, 52, 17, 9, 24, 58, 2, 99, 27, 19, 97, 84, 54, 76, 69, 12, 81, 30, 1, 34, 86, 98, 43, 94, 21, 90, 74, 91, 45]
nv: 10 || Train: 13.602 || Val: 10.901
nv: 15 || Train: 27.98 || Val: 18.023
nv: 20 || Train: 33.418 || Val: 19.767
nv: 25 || Train: 41.812 || Val: 23.159
nv: 30 || Train: 45.858 || Val: 23.934
nv: 35 || Train: 52.277 || Val: 26.163
nv: 40 || Train: 56.856 || Val: 27.18
nv: 45 || Train: 60.744 || Val: 30.329
nv: 50 || Train: 62.1 || Val: 31.928
nv: 55 || Train: 63.723 || Val: 33.576
nv: 60 || Train: 65.371 || Val: 33.285
nv: 65 || Train: 66.63 || Val: 33.721
nv: 70 || Train: 67.115 || Val: 34.69
nv: 75 || Train: 68.156 || Val: 36.386
nv: 80 || Train: 69.053 || Val: 36.628
nv: 85 || Train: 69.295 || Val: 36.483
nv: 90 || Train: 70.3 || Val: 36.773
nv: 95 || Train: 71.633 || Val: 37.936
nv: 100 || Train: 72.069 || Val: 38.517
nv: 102 || Train: 72.178 || Val: 38.663
5
4
3
2
1
3
2
1
0

      Counts Attributes  Train Acc  Test Seen Acc  Test Unseen Acc
0          5     (101,)     61.240         28.953           46.736
1          4       (1,)      0.223          0.078            2.292
2          3       (0,)      0.000          0.000            0.000
3          2       (0,)      0.000          0.000            0.000
4          1       (0,)      0.000          0.000            0.000
5        5-4     (102,)     61.531         29.419           47.153
6      5-4-3     (102,)     61.531         29.419           47.153
7    5-4-3-2     (102,)     61.531         29.419           47.153
8  5-4-3-2-1     (102,)     61.531         29.419           47.153

# Animals

In [7]:
#################
### Arguments ###
#################
class Arguments:
    def __init__(self, dataset,seed,mode):
        self.dataset = dataset
        self.seed = seed
        self.mode = mode
        
         
DECIMAL_NUMBERS        = 3
FOLDS                  = 5
scaler_str             = 'Standard'     # ['Standard','MinMax']
orig_attribute         = False # Attributos originales u otros
debug                  = True 
SHOW                   = True

step                     = 5  # Paso de atributos a seleccionar [a, a+step, a+2*step, ...]
hitk = 1    
args = Arguments('AWA2',42,'rfe') # MODE = RFE


#################
##### SetUp #####
#################
random.seed(args.seed)
np.random.seed(args.seed)
print(f"You've selected {args.dataset} dataset")
print(f"You've selected {args.mode} mode")
random_mode = False if args.mode == 'rfe' else True 
rfe_mode    = False if args.mode == 'random' else True

# Set up the path to the data
# Set up the path to the data
path_dir                  = pathlib.Path('data/')
path_data                 = path_dir / args.dataset  
results_dir               = pathlib.Path(f'Results/HAIS_v2/{args.dataset}') 


path_results_rfe_train_val    = results_dir / f'Wrapper{args.dataset}-RFE-train-val.csv'
path_results_random_val       = results_dir / f'Wrapper{args.dataset}-Random-val.csv' 
path_results_rfe_val_val      = results_dir / f'Wrapper{args.dataset}-RFE-val-val.csv'
path_results_random_simple    = results_dir / f'Wrapper{args.dataset}-Random-simple.csv' 

path_masks_rfe_train_val    = results_dir / f'Masks_{args.dataset}-RFE-train-val.csv'
path_masks_random_val       = results_dir / f'Masks_{args.dataset}-Random-val.csv' 
path_masks_rfe_val_val      = results_dir / f'Masks_{args.dataset}-RFE-val-val.csv'
path_masks_random_simple    = results_dir / f'Masks_{args.dataset}-Random-simple.csv' 

path_oracle_rfe_train_val    = results_dir / f'Oracle_Wrapper_{args.dataset}-RFE-train-val.csv'
path_oracle_random_val       = results_dir / f'Oracle_Wrapper_{args.dataset}-Random-val.csv' 
path_oracle_rfe_val_val      = results_dir / f'Oracle_Wrapper_{args.dataset}-RFE-val-val.csv'
path_oracle_random_simple    = results_dir / f'Oracle_Wrapper_{args.dataset}-Random-simple.csv' 

path_conteo_rfe_train_val    = results_dir / f'Conteo_{args.dataset}-RFE-train-val.csv'
path_conteo_random_val       = results_dir / f'Conteo_{args.dataset}-Random-val.csv' 
path_conteo_rfe_val_val      = results_dir / f'Conteo_{args.dataset}-RFE-val-val.csv'
path_conteo_random_simple    = results_dir / f'Conteo_{args.dataset}-Random-simple.csv' 



# Load the data
matcontent, att_splits = load_data_from_path(path_data, show = False)

"""
Comentar que en los datos de este datasets viene una partición establecida para train y val. Sin embargo, la partición de 'val' no contempla clases Unseen. Por tanto no la vamos usar.
Crearemos una partición de validación para clases Seen y Unseen a partir de la partición de test. 
Como conjunto de entrenamiento usaremos el que viene dado por los índices de la variable 'trainval_loc' en att_splits. 
Los índices de las varaibles 'train_loc' y 'val_loc' no los vamos a usar.
"""
# Get the data from att_splits dictionary
allclasses_names            = att_splits['allclasses_names']
original_att                = att_splits['original_att'].T.astype('float')  # Attributos originales
attribute                   = att_splits['att'].T.astype('float')           # Atributos que no se de donde salen, pero son los que usan <=== IMPORTANTE
# Indixes of the instances in the train, test and validation sets
test_unseen_loc             = att_splits['test_unseen_loc'].squeeze() - 1
test_seen_loc               = att_splits['test_seen_loc'].squeeze() - 1
trainval_loc                = att_splits['trainval_loc'].squeeze() - 1      # En caso de no usar validación, aquí estara todo el entrenamiento
train_loc                   = att_splits['train_loc'].squeeze() - 1         # Esto es si usamos validacion, ver comentario arriba
val_loc                     = att_splits['val_loc'].squeeze() -1            # Esto es si usamos validacion, ver comentario arriba
# Get the dta from matcontent dictionary
feature =  matcontent['features'].T                       # Feature Matrix (Number of instances x Number of features)
labels  =  matcontent['labels'].astype(int).squeeze() - 1 # Ponemos que sea entero, eliminamos la dimension extra y con el '-1' movemos el rango de [1,200] a [0,199]

random.shuffle(trainval_loc)
# Es importante usar aquí la matrices feature y labels originales
trainval_feature = feature[trainval_loc]
trainval_labels  = labels[trainval_loc]
trainval_classes = np.unique(trainval_labels)
random.shuffle(trainval_classes)

classes_per_fold = int(trainval_classes.shape[0] / FOLDS)
acarreo          = trainval_classes.shape[0] % FOLDS


# Get attributes and preprocessing them
attribute = original_att if orig_attribute else attribute
attribute = scaler_data(get_scaler(scaler_str),attribute)




#################
##### FOLDS #####
#################
folds = []
for i in range(FOLDS):
    
    # Gather data for the fold
    start = i * classes_per_fold
    end   = (i + 1) * classes_per_fold if i != FOLDS - 1 else (i + 1) * classes_per_fold + acarreo
    
    fold_i_val_classes       = trainval_classes[start:end] # Unseen
    fold_i_training_classes  = [x for x in trainval_classes if x not in fold_i_val_classes] # Seen
    
    fold_i_val_loc           = np.where(np.isin(trainval_labels, fold_i_val_classes)) # index for val
    fold_i_training_loc      = np.where(np.isin(trainval_labels, fold_i_training_classes)) # Index for training
    # np.isin(element,test_element) Calculates element in test_elements, broadcasting over element only. 
    # #Returns a boolean array of the same shape as element that is True where an element of element is in 
    # #test_elements and False otherwise.
    # np.where(lists[bool]) returns the indexes of the True values in the lists
    
    assert np.intersect1d(fold_i_val_loc, fold_i_training_loc).shape[0] == 0, f"Error: Problems found in creating folds {i}. Val and training classes are not disjoint"
    assert np.intersect1d(fold_i_val_classes, fold_i_training_classes).shape[0] == 0, f"Error: Problems found in creating folds {i}. Val and training classes are not disjoint"
    assert all([i not in fold_i_training_classes for i in trainval_labels[fold_i_val_loc]]), f"Error: Problems found in creating folds {i}"
    assert all([i not in fold_i_val_classes for i in trainval_labels[fold_i_training_loc]]), f"Error: Problems found in creating folds {i}"

    fold_i_training_features = trainval_feature[fold_i_training_loc]
    fold_i_val_features      = trainval_feature[fold_i_val_loc]
    fold_i_training_labels   = trainval_labels[fold_i_training_loc]
    fold_i_val_labels        = trainval_labels[fold_i_val_loc]
    fold_i_ss_val            = gen_ss_from_data(fold_i_val_labels,attribute)
    fold_i_ss_training       = gen_ss_from_data(fold_i_training_labels,attribute)
    
    assert np.intersect1d(np.unique(fold_i_val_labels),np.unique(fold_i_training_labels)).shape[0] == 0, f"Los conjuntos del fold {i+1} de etiquetas no son disjuntos"
    
    # Preprocess the data
    fold_i_training_features, fold_i_val_features = scaler_data(get_scaler(scaler_str),
                                                                fold_i_training_features,
                                                                fold_i_val_features)
    
    # Creating Datasets 
    fold_training = Dataset(features = fold_i_training_features, 
                            labels   = fold_i_training_labels, 
                            att      = fold_i_ss_training, 
                            mode     = 'train')
    
    fold_val      = Dataset(features = fold_i_val_features,
                            labels   = fold_i_val_labels,
                            att      = fold_i_ss_val,
                            mode     = 'val')
    
    fold = StackedDataset({'train':fold_training, 'val':fold_val})
    
    folds.append(fold)
    
    if SHOW:
        print(f"Fold {i+1} || Val Classes {np.unique(fold_i_val_labels).shape} - {fold_i_val_labels.shape} instances || Training Classes {np.unique(fold_i_training_labels).shape} - {fold_i_training_labels.shape} instances")

You've selected AWA2 dataset
You've selected rfe mode
Fold 1 || Val Classes (8,) - (4631,) instances || Training Classes (32,) - (18896,) instances
Fold 2 || Val Classes (8,) - (5050,) instances || Training Classes (32,) - (18477,) instances
Fold 3 || Val Classes (8,) - (4616,) instances || Training Classes (32,) - (18911,) instances
Fold 4 || Val Classes (8,) - (4629,) instances || Training Classes (32,) - (18898,) instances
Fold 5 || Val Classes (8,) - (4601,) instances || Training Classes (32,) - (18926,) instances

## Train VAl

In [8]:
args = Arguments('AWA2',42,'rfe') # MODE = RFE
random.seed(args.seed)
np.random.seed(args.seed)
print(f"You've selected {args.dataset} dataset")
print(f"You've selected {args.mode} mode")
random_mode = False if args.mode == 'rfe' else True 
rfe_mode    = False if args.mode == 'random' else True

vattributes = np.arange(10, attribute.shape[1], step)
if attribute.shape[1] % step != 0:
    vattributes = np.append(vattributes, attribute.shape[1])

conteo          = np.zeros(attribute.shape[1])
best_folds_configuration = [] # Mejor configurración de atributos seleccionados en cada uno de los folds
for i, fold in enumerate(folds):

    print(f"Fold {i+1}...")

    training_data = fold.datasets['train']
    val_data      = fold.datasets['val']

    attributes_X_train = training_data.att.copy()

    rfe = RFE(estimator = None, estimator_name = 'SAE', n_features_to_select = 1, step = 1, verbose = True)
    rfe.fit(training_data.features, training_data.att,training_data.labels)
    ranking = rfe.get_ranking()
    
    fold_i_att_acc = {'Attributes': [],
                      'Train Acc': [],
                      'Val Acc': [],
                      'Mask':[]}
    
    for nv in vattributes:
        
        mask = ranking <= nv
        W = SAE(training_data.features.T, training_data.att[:,mask].T,500000) 
        # Training Acc
        gt_ss_training_adapted  = attribute[training_data.classes][:,mask]
        semantic_predicted = np.dot(training_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, training_data.classes,training_data.labels)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        # Val Acc
        gt_ss_val_adapted    = attribute[val_data.classes][:,mask]
        semantic_predicted = np.dot(val_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, val_data.classes,val_data.labels)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        # Save results
        fold_i_att_acc['Attributes'].append(nv)
        fold_i_att_acc['Train Acc'].append(zsl_accuracy_train)
        fold_i_att_acc['Val Acc'].append(zsl_accuracy1_unseen)
        fold_i_att_acc['Mask'].append(mask)
        
        if debug:
            print(f"nv: {nv} || Train: {zsl_accuracy_train} || Val: {zsl_accuracy1_unseen}")
    # Saving the best configuration of the fold
    fold_i_att_acc = pd.DataFrame(fold_i_att_acc).sort_values(by = 'Val Acc', ascending = False)
    best_folds_configuration.append(fold_i_att_acc.iloc[0])
    

for res in best_folds_configuration:
    conteo = conteo + np.asarray(res['Mask']).astype(int)
    
    
df = {}
for i in range(len(best_folds_configuration)):
    df[i] = best_folds_configuration[i].to_dict()
df = pd.DataFrame(df).T

if rfe_mode: 
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_rfe_train_val)
else:
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_random_val)
    
    
    
    
# Evaluamos en test 
test_results = {'Counts':[],'Attributes':[],'Train Acc':[],'Test Seen Acc':[],'Test Unseen Acc':[]}
j = 1
cadena = '5'
for i in range(FOLDS*2-1):
    if i < FOLDS:
        test_results['Counts'].append(str(FOLDS-i))
        test_results['Attributes'].append(np.where(conteo==FOLDS-i)[0].shape)
        mejores = np.where(conteo==FOLDS-i)[0]

    else:
        cadena = cadena+'-'+str(FOLDS-j)
        test_results['Counts'].append(cadena)
        test_results['Attributes'].append(np.where(conteo>=FOLDS-j)[0].shape)
        mejores = np.where(conteo>=FOLDS-j)[0]
        j+=1

    
    
    if mejores.shape[0] > 0:
        # Training
        training_feature = feature[trainval_loc]
        training_label   = labels[trainval_loc]
        ss_training      = gen_ss_from_data(training_label,attribute)
        # Get test
        test_unseen_feature = feature[test_unseen_loc]
        test_unseen_label   = labels[test_unseen_loc]
        ss_test_unseen      = gen_ss_from_data(test_unseen_label,attribute)
        test_seen_feature = feature[test_seen_loc]
        test_seen_label   = labels[test_seen_loc]
        ss_test_seen      = gen_ss_from_data(test_seen_label,attribute)
        # Preprocessing
        scaler = get_scaler(scaler_str)
        scaler.fit(training_feature)
        training_feature = scaler.transform(training_feature)
        test_unseen_feature = scaler.transform(test_unseen_feature)
        test_seen_feature = scaler.transform(test_seen_feature)
        # Fit the model
        W = SAE(training_feature.T, ss_training[:,mejores].T,500000) 
        gt_ss_training_adapted  = attribute[np.unique(training_label)][:,mejores]
        semantic_predicted = np.dot(training_feature, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, np.unique(training_label),training_label)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        test_results['Train Acc'].append(zsl_accuracy_train)
        # Evaluo en test seen
        gt_ss_val_adapted    = attribute[np.unique(test_seen_label)][:,mejores]
        semantic_predicted = np.dot(test_seen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_seen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_seen_label),test_seen_label)
        zsl_accuracy1_seen = round(zsl_accuracy1_seen,DECIMAL_NUMBERS)
        test_results['Test Seen Acc'].append(zsl_accuracy1_seen)
        # Evaluo en test unseen
        gt_ss_val_adapted    = attribute[np.unique(test_unseen_label)][:,mejores]
        semantic_predicted = np.dot(test_unseen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_unseen_label),test_unseen_label)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        test_results['Test Unseen Acc'].append(zsl_accuracy1_unseen)
    else:
        test_results['Train Acc'].append(0)
        test_results['Test Seen Acc'].append(0)
        test_results['Test Unseen Acc'].append(0)
    
if rfe_mode:
    pd.DataFrame(test_results).to_csv(path_oracle_rfe_train_val)
else:
    pd.DataFrame(test_results).to_csv(path_oracle_random_val)
    
pd.DataFrame(test_results)

You've selected AWA2 dataset
You've selected rfe mode
Fold 1...
Ranking: [30, 6, 3, 32, 66, 24, 80, 41, 43, 20, 5, 52, 4, 83, 62, 42, 17, 33, 38, 12, 75, 11, 79, 55, 34, 72, 51, 27, 48, 61, 8, 23, 58, 36, 0, 76, 40, 78, 26, 7, 59, 15, 81, 28, 65, 54, 77, 21, 67, 22, 69, 53, 2, 9, 60, 31, 35, 82, 47, 84, 45, 49, 19, 44, 18, 50, 16, 29, 74, 64, 10, 14, 46, 39, 71, 1, 56, 13, 70, 57, 63, 68, 25, 37, 73]
nv: 10 || Train: 88.172 || Val: 54.697
nv: 15 || Train: 92.692 || Val: 57.871
nv: 20 || Train: 94.74 || Val: 55.042
nv: 25 || Train: 95.258 || Val: 62.773
nv: 30 || Train: 95.57 || Val: 65.385
nv: 35 || Train: 96.084 || Val: 72.403
nv: 40 || Train: 96.041 || Val: 76.571
nv: 45 || Train: 96.031 || Val: 76.247
nv: 50 || Train: 96.206 || Val: 79.162
nv: 55 || Train: 96.274 || Val: 81.214
nv: 60 || Train: 96.306 || Val: 81.689
nv: 65 || Train: 96.417 || Val: 82.531
nv: 70 || Train: 96.47 || Val: 78.493
nv: 75 || Train: 96.507 || Val: 79.292
nv: 80 || Train: 96.565 || Val: 85.727
Fold 2...
Ranking: [10, 30, 6, 32, 80, 56, 20, 53, 60, 81, 55, 74, 66, 21, 45, 0, 41, 64, 24, 11, 73, 38, 12, 42, 58, 76, 36, 1, 79, 15, 5, 14, 72, 16, 31, 18, 35, 50, 29, 82, 75, 83, 26, 84, 43, 13, 63, 52, 54, 49, 40, 65, 27, 23, 77, 48, 78, 33, 2, 9, 25, 70, 17, 44, 69, 61, 47, 59, 62, 71, 4, 67, 19, 46, 22, 7, 57, 51, 8, 37, 34, 68, 28, 3, 39]
nv: 10 || Train: 90.615 || Val: 42.95
nv: 15 || Train: 95.438 || Val: 41.267
nv: 20 || Train: 96.163 || Val: 51.703
nv: 25 || Train: 96.076 || Val: 54.079
nv: 30 || Train: 96.504 || Val: 53.05
nv: 35 || Train: 96.672 || Val: 54.911
nv: 40 || Train: 96.904 || Val: 56.198
nv: 45 || Train: 97.023 || Val: 58.535
nv: 50 || Train: 96.953 || Val: 56.059
nv: 55 || Train: 97.202 || Val: 55.703
nv: 60 || Train: 97.37 || Val: 57.465
nv: 65 || Train: 97.429 || Val: 58.119
nv: 70 || Train: 97.435 || Val: 57.347
nv: 75 || Train: 97.467 || Val: 57.129
nv: 80 || Train: 97.429 || Val: 59.03
Fold 3...
Ranking: [6, 10, 35, 51, 5, 41, 52, 31, 56, 21, 84, 9, 66, 24, 27, 11, 12, 0, 50, 36, 75, 83, 82, 78, 2, 48, 69, 70, 14, 79, 76, 64, 15, 7, 28, 80, 55, 29, 81, 25, 74, 62, 77, 17, 8, 18, 26, 72, 3, 49, 38, 30, 42, 45, 58, 47, 34, 22, 40, 13, 61, 71, 20, 60, 63, 65, 44, 54, 39, 46, 73, 59, 67, 33, 19, 57, 23, 16, 53, 1, 68, 37, 4, 32, 43]
nv: 10 || Train: 93.025 || Val: 48.527
nv: 15 || Train: 93.506 || Val: 50.78
nv: 20 || Train: 95.077 || Val: 61.763
nv: 25 || Train: 95.484 || Val: 64.146
nv: 30 || Train: 95.833 || Val: 59.467
nv: 35 || Train: 96.008 || Val: 58.947
nv: 40 || Train: 96.071 || Val: 59.164
nv: 45 || Train: 96.209 || Val: 58.146
nv: 50 || Train: 96.378 || Val: 56.153
nv: 55 || Train: 96.536 || Val: 55.698
nv: 60 || Train: 96.552 || Val: 53.51
nv: 65 || Train: 96.647 || Val: 52.145
nv: 70 || Train: 96.759 || Val: 51.971
nv: 75 || Train: 96.711 || Val: 54.549
nv: 80 || Train: 96.69 || Val: 55.654
Fold 4...
Ranking: [40, 30, 47, 32, 39, 10, 50, 4, 16, 41, 24, 33, 12, 63, 8, 60, 67, 53, 83, 26, 35, 74, 34, 17, 11, 76, 31, 20, 66, 69, 3, 55, 51, 14, 64, 56, 61, 7, 9, 58, 15, 13, 46, 78, 73, 22, 79, 42, 77, 57, 27, 21, 81, 28, 54, 75, 6, 82, 29, 62, 72, 19, 70, 37, 49, 52, 65, 71, 84, 5, 45, 0, 80, 2, 59, 36, 43, 68, 18, 1, 44, 38, 25, 23, 48]
nv: 10 || Train: 89.92 || Val: 58.501
nv: 15 || Train: 94.904 || Val: 66.753
nv: 20 || Train: 96.127 || Val: 69.756
nv: 25 || Train: 96.465 || Val: 70.274
nv: 30 || Train: 96.523 || Val: 70.145
nv: 35 || Train: 96.857 || Val: 73.212
nv: 40 || Train: 96.92 || Val: 73.817
nv: 45 || Train: 97.111 || Val: 74.401
nv: 50 || Train: 97.238 || Val: 77.943
nv: 55 || Train: 97.285 || Val: 78.311
nv: 60 || Train: 97.317 || Val: 78.138
nv: 65 || Train: 97.386 || Val: 75.632
nv: 70 || Train: 97.534 || Val: 75.589
nv: 75 || Train: 97.524 || Val: 76.129
nv: 80 || Train: 97.587 || Val: 74.163
Fold 5...
Ranking: [6, 66, 30, 5, 41, 10, 33, 52, 24, 20, 27, 0, 40, 32, 50, 58, 61, 51, 55, 12, 42, 47, 80, 78, 43, 71, 1, 39, 14, 62, 34, 60, 81, 15, 53, 75, 79, 82, 77, 16, 11, 38, 21, 36, 46, 70, 22, 28, 54, 4, 63, 7, 57, 25, 68, 44, 45, 59, 35, 31, 84, 76, 72, 13, 74, 23, 3, 65, 73, 18, 8, 2, 17, 64, 9, 37, 49, 67, 56, 19, 69, 48, 29, 83, 26]
nv: 10 || Train: 93.168 || Val: 42.512
nv: 15 || Train: 95.012 || Val: 54.749
nv: 20 || Train: 95.736 || Val: 58.466
nv: 25 || Train: 96.021 || Val: 61.921
nv: 30 || Train: 96.243 || Val: 66.094
nv: 35 || Train: 96.444 || Val: 63.638
nv: 40 || Train: 96.402 || Val: 64.051
nv: 45 || Train: 96.55 || Val: 66.464
nv: 50 || Train: 96.502 || Val: 65.92
nv: 55 || Train: 96.465 || Val: 65.095
nv: 60 || Train: 96.449 || Val: 67.116
nv: 65 || Train: 96.465 || Val: 66.29
nv: 70 || Train: 96.555 || Val: 65.181
nv: 75 || Train: 96.661 || Val: 68.311
nv: 80 || Train: 96.745 || Val: 68.833

      Counts Attributes  Train Acc  Test Seen Acc  Test Unseen Acc
0          5      (11,)     90.653         86.348           42.260
1          4      (49,)     95.325         92.095           38.885
2          3      (24,)     93.582         89.918           26.855
3          2       (1,)      4.259          3.808           16.340
4          1       (0,)      0.000          0.000            0.000
5        5-4      (60,)     95.575         92.333           44.547
6      5-4-3      (84,)     95.856         92.894           39.189
7    5-4-3-2      (85,)     95.856         92.860           39.151
8  5-4-3-2-1      (85,)     95.856         92.860           39.151

## Val Val

In [9]:
args = Arguments('AWA2',42,'rfe') # MODE = RFE


random.seed(args.seed)
np.random.seed(args.seed)
print(f"You've selected {args.dataset} dataset")
print(f"You've selected {args.mode} mode")
random_mode = False if args.mode == 'rfe' else True 
rfe_mode    = False if args.mode == 'random' else True




vattributes = np.arange(10, attribute.shape[1], step)
if attribute.shape[1] % step != 0:
    vattributes = np.append(vattributes, attribute.shape[1])

conteo          = np.zeros(attribute.shape[1])
best_folds_configuration = [] # Mejor configurración de atributos seleccionados en cada uno de los folds
for i, fold in enumerate(folds):

    print(f"Fold {i+1}...")

    training_data = fold.datasets['train']
    val_data      = fold.datasets['val']



    rfe = RFE(estimator = None, estimator_name = 'SAE', n_features_to_select = 1, step = 1, verbose = True)
    rfe.fit(val_data.features, val_data.att,val_data.labels)
    ranking = rfe.get_ranking()
    
    fold_i_att_acc = {'Attributes': [],
                      'Train Acc': [],
                      'Val Acc': [],
                      'Mask':[]}
    
    for nv in vattributes:
        
        mask = ranking <= nv
        W = SAE(training_data.features.T, training_data.att[:,mask].T,500000) 
        # Training Acc
        gt_ss_training_adapted  = attribute[training_data.classes][:,mask]
        semantic_predicted = np.dot(training_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, training_data.classes,training_data.labels)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        # Val Acc
        gt_ss_val_adapted    = attribute[val_data.classes][:,mask]
        semantic_predicted = np.dot(val_data.features, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, val_data.classes,val_data.labels)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        # Save results
        fold_i_att_acc['Attributes'].append(nv)
        fold_i_att_acc['Train Acc'].append(zsl_accuracy_train)
        fold_i_att_acc['Val Acc'].append(zsl_accuracy1_unseen)
        fold_i_att_acc['Mask'].append(mask)
        
        if debug:
            print(f"nv: {nv} || Train: {zsl_accuracy_train} || Val: {zsl_accuracy1_unseen}")
    # Saving the best configuration of the fold
    fold_i_att_acc = pd.DataFrame(fold_i_att_acc).sort_values(by = 'Val Acc', ascending = False)
    best_folds_configuration.append(fold_i_att_acc.iloc[0])
    

for res in best_folds_configuration:
    conteo = conteo + np.asarray(res['Mask']).astype(int)
   
   
   
   
df = {}
for i in range(len(best_folds_configuration)):
    df[i] = best_folds_configuration[i].to_dict()
df = pd.DataFrame(df).T

if rfe_mode: # Los mejores resultados de cada fold y el conteo
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_rfe_val_val)
else:
    df[['Attributes','Train Acc', 'Val Acc','Mask']].to_csv(path_results_random_val)
    
    
    
    
    
    
    
    
# Evaluamos en test 
test_results = {'Counts':[],'Attributes':[],'Train Acc':[],'Test Seen Acc':[],'Test Unseen Acc':[]}
j = 1
cadena = '5'
for i in range(FOLDS*2-1):
    if i < FOLDS:
        test_results['Counts'].append(str(FOLDS-i))
        test_results['Attributes'].append(np.where(conteo==FOLDS-i)[0].shape)
        mejores = np.where(conteo==FOLDS-i)[0]
        print(FOLDS-i)
    else:
        cadena = cadena+'-'+str(FOLDS-j)
        test_results['Counts'].append(cadena)
        test_results['Attributes'].append(np.where(conteo>=FOLDS-j)[0].shape)
        mejores = np.where(conteo>=FOLDS-j)[0]
        j+=1
        print(FOLDS-j)
    
    
    if mejores.shape[0] > 0:
        # Training
        training_feature = feature[trainval_loc].copy()
        training_label   = labels[trainval_loc].copy()
        ss_training      = gen_ss_from_data(training_label,attribute)
        # Get test
        test_unseen_feature = feature[test_unseen_loc].copy()
        test_unseen_label   = labels[test_unseen_loc].copy()
        ss_test_unseen      = gen_ss_from_data(test_unseen_label,attribute)
        test_seen_feature = feature[test_seen_loc].copy()
        test_seen_label   = labels[test_seen_loc].copy()
        ss_test_seen      = gen_ss_from_data(test_seen_label,attribute)
        # Preprocessing
        scaler = get_scaler(scaler_str)
        scaler.fit(training_feature)
        training_feature = scaler.transform(training_feature)
        test_unseen_feature = scaler.transform(test_unseen_feature)
        test_seen_feature = scaler.transform(test_seen_feature)
        # Fit the model
        W = SAE(training_feature.T, ss_training[:,mejores].T,500000) 
        gt_ss_training_adapted  = attribute[np.unique(training_label)][:,mejores]
        semantic_predicted = np.dot(training_feature, normalizeFeature(W).transpose())
        [zsl_accuracy_train, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_training_adapted, hitk, np.unique(training_label),training_label)
        zsl_accuracy_train = round(zsl_accuracy_train,DECIMAL_NUMBERS)
        test_results['Train Acc'].append(zsl_accuracy_train)
        # Evaluo en test seen
        gt_ss_val_adapted    = attribute[np.unique(test_seen_label)][:,mejores]
        semantic_predicted = np.dot(test_seen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_seen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_seen_label),test_seen_label)
        zsl_accuracy1_seen = round(zsl_accuracy1_seen,DECIMAL_NUMBERS)
        test_results['Test Seen Acc'].append(zsl_accuracy1_seen)
        # Evaluo en test unseen
        gt_ss_val_adapted    = attribute[np.unique(test_unseen_label)][:,mejores]
        semantic_predicted = np.dot(test_unseen_feature, normalizeFeature(W).transpose())
        [zsl_accuracy1_unseen, y_hit_k] = zsl_acc(semantic_predicted, gt_ss_val_adapted, hitk, np.unique(test_unseen_label),test_unseen_label)
        zsl_accuracy1_unseen = round(zsl_accuracy1_unseen,DECIMAL_NUMBERS)
        test_results['Test Unseen Acc'].append(zsl_accuracy1_unseen)
    else:
        test_results['Train Acc'].append(0)
        test_results['Test Seen Acc'].append(0)
        test_results['Test Unseen Acc'].append(0)
    
if rfe_mode:
    pd.DataFrame(test_results).to_csv(path_oracle_rfe_val_val)
else:
    pd.DataFrame(test_results).to_csv(path_oracle_random_val)
    
pd.DataFrame(test_results)

You've selected AWA2 dataset
You've selected rfe mode
Fold 1...
Ranking: [10, 35, 63, 74, 1, 67, 40, 13, 62, 0, 12, 75, 42, 36, 39, 43, 3, 5, 26, 30, 51, 83, 73, 18, 64, 65, 11, 16, 14, 41, 47, 9, 57, 82, 46, 54, 29, 71, 28, 81, 53, 60, 4, 32, 80, 68, 45, 8, 15, 25, 38, 34, 55, 66, 33, 79, 2, 72, 84, 61, 56, 22, 49, 58, 48, 7, 20, 50, 27, 31, 6, 19, 78, 59, 77, 24, 44, 69, 70, 23, 17, 52, 37, 21, 76]
nv: 10 || Train: 90.543 || Val: 34.55
nv: 15 || Train: 92.448 || Val: 47.247
nv: 20 || Train: 94.242 || Val: 69.1
nv: 25 || Train: 94.761 || Val: 67.221
nv: 30 || Train: 94.692 || Val: 70.244
nv: 35 || Train: 95.232 || Val: 74.476
nv: 40 || Train: 95.533 || Val: 69.445
nv: 45 || Train: 95.518 || Val: 68.646
nv: 50 || Train: 95.899 || Val: 68.387
nv: 55 || Train: 96.036 || Val: 80.76
nv: 60 || Train: 96.068 || Val: 81.926
nv: 65 || Train: 96.258 || Val: 83.783
nv: 70 || Train: 96.296 || Val: 84.517
nv: 75 || Train: 96.428 || Val: 85.338
nv: 80 || Train: 96.507 || Val: 85.943
Fold 2...
Ranking: [30, 20, 0, 57, 65, 22, 76, 75, 51, 64, 48, 80, 36, 84, 79, 54, 42, 52, 66, 23, 61, 71, 5, 13, 25, 59, 10, 78, 27, 77, 15, 7, 24, 26, 45, 33, 31, 44, 21, 2, 60, 37, 14, 8, 68, 1, 41, 19, 29, 58, 67, 82, 55, 40, 16, 6, 50, 53, 32, 83, 81, 11, 39, 70, 4, 56, 34, 38, 62, 28, 63, 47, 3, 12, 46, 72, 49, 18, 69, 9, 43, 17, 35, 74, 73]
nv: 10 || Train: 91.573 || Val: 28.653
nv: 15 || Train: 94.561 || Val: 42.257
nv: 20 || Train: 95.99 || Val: 38.376
nv: 25 || Train: 96.466 || Val: 43.168
nv: 30 || Train: 96.92 || Val: 45.267
nv: 35 || Train: 96.872 || Val: 44.554
nv: 40 || Train: 96.991 || Val: 49.188
nv: 45 || Train: 97.137 || Val: 49.624
nv: 50 || Train: 97.256 || Val: 49.05
nv: 55 || Train: 97.391 || Val: 55.01
nv: 60 || Train: 97.386 || Val: 55.446
nv: 65 || Train: 97.462 || Val: 57.228
nv: 70 || Train: 97.429 || Val: 55.663
nv: 75 || Train: 97.435 || Val: 56.891
nv: 80 || Train: 97.429 || Val: 58.139
Fold 3...
Ranking: [67, 63, 14, 13, 62, 40, 39, 11, 71, 15, 46, 47, 30, 41, 9, 12, 59, 32, 50, 66, 42, 16, 80, 25, 57, 8, 65, 49, 21, 35, 69, 28, 83, 3, 64, 19, 48, 10, 27, 36, 4, 51, 74, 38, 78, 17, 56, 54, 18, 77, 34, 6, 22, 7, 73, 58, 72, 68, 61, 75, 26, 20, 37, 45, 84, 44, 60, 53, 24, 33, 29, 70, 5, 1, 0, 52, 55, 76, 79, 82, 43, 31, 81, 23, 2]
nv: 10 || Train: 85.929 || Val: 45.841
nv: 15 || Train: 92.671 || Val: 58.211
nv: 20 || Train: 94.865 || Val: 60.312
nv: 25 || Train: 95.627 || Val: 58.86
nv: 30 || Train: 95.833 || Val: 60.659
nv: 35 || Train: 96.008 || Val: 59.684
nv: 40 || Train: 96.193 || Val: 61.157
nv: 45 || Train: 96.293 || Val: 58.297
nv: 50 || Train: 96.219 || Val: 58.731
nv: 55 || Train: 96.251 || Val: 58.471
nv: 60 || Train: 96.33 || Val: 57.344
nv: 65 || Train: 96.473 || Val: 54.224
nv: 70 || Train: 96.547 || Val: 56.066
nv: 75 || Train: 96.669 || Val: 54.528
nv: 80 || Train: 96.716 || Val: 57.062
Fold 4...
Ranking: [72, 11, 84, 81, 82, 26, 12, 62, 63, 3, 44, 22, 69, 13, 27, 31, 4, 38, 17, 47, 75, 0, 65, 36, 29, 9, 32, 73, 18, 30, 78, 46, 59, 10, 52, 19, 49, 34, 2, 7, 53, 80, 23, 40, 79, 39, 8, 33, 67, 83, 60, 43, 64, 21, 45, 77, 48, 50, 6, 70, 55, 25, 66, 74, 58, 68, 24, 37, 51, 71, 42, 28, 61, 16, 14, 5, 1, 56, 76, 57, 20, 41, 35, 54, 15]
nv: 10 || Train: 92.941 || Val: 44.934
nv: 15 || Train: 95.074 || Val: 49.687
nv: 20 || Train: 95.359 || Val: 57.269
nv: 25 || Train: 96.148 || Val: 62.67
nv: 30 || Train: 96.518 || Val: 67.336
nv: 35 || Train: 96.656 || Val: 68.957
nv: 40 || Train: 96.947 || Val: 68.373
nv: 45 || Train: 97.042 || Val: 71.074
nv: 50 || Train: 97.047 || Val: 74.897
nv: 55 || Train: 97.206 || Val: 72.348
nv: 60 || Train: 97.317 || Val: 72.672
nv: 65 || Train: 97.397 || Val: 73.493
nv: 70 || Train: 97.402 || Val: 71.549
nv: 75 || Train: 97.492 || Val: 72.089
nv: 80 || Train: 97.534 || Val: 72.219
Fold 5...
Ranking: [21, 52, 51, 22, 78, 79, 61, 65, 27, 12, 43, 36, 41, 75, 42, 25, 55, 7, 40, 11, 73, 39, 58, 18, 24, 29, 45, 64, 16, 56, 68, 70, 48, 50, 20, 47, 38, 63, 15, 53, 2, 32, 4, 3, 13, 60, 37, 57, 28, 66, 14, 1, 54, 62, 76, 46, 74, 82, 71, 17, 31, 49, 5, 59, 26, 6, 77, 67, 72, 81, 83, 9, 0, 44, 33, 8, 69, 19, 35, 23, 30, 10, 80, 84, 34]
nv: 10 || Train: 90.442 || Val: 33.514
nv: 15 || Train: 92.217 || Val: 41.708
nv: 20 || Train: 94.299 || Val: 43.404
nv: 25 || Train: 95.197 || Val: 50.619
nv: 30 || Train: 95.873 || Val: 53.88
nv: 35 || Train: 95.9 || Val: 55.901
nv: 40 || Train: 96.143 || Val: 61.008
nv: 45 || Train: 96.021 || Val: 63.856
nv: 50 || Train: 96.238 || Val: 69.289
nv: 55 || Train: 96.412 || Val: 70.202
nv: 60 || Train: 96.534 || Val: 69.702
nv: 65 || Train: 96.555 || Val: 70.506
nv: 70 || Train: 96.618 || Val: 71.593
nv: 75 || Train: 96.671 || Val: 71.55
nv: 80 || Train: 96.724 || Val: 70.028
5
4
3
2
1
3
2
1
0

      Counts Attributes  Train Acc  Test Seen Acc  Test Unseen Acc
0          5      (21,)     92.341         88.388           49.703
1          4      (33,)     94.143         90.785           29.433
2          3      (26,)     93.080         90.020           33.982
3          2       (5,)     60.195         55.423           38.532
4          1       (0,)      0.000          0.000            0.000
5        5-4      (54,)     95.316         91.942           34.652
6      5-4-3      (80,)     95.886         92.860           38.140
7    5-4-3-2      (85,)     95.856         92.860           39.151
8  5-4-3-2-1      (85,)     95.856         92.860           39.151